"""Pricing of fixed-rate domestic tariffs.

Synthetic Forward Curve law: a customer's fixed unit rate is derived from a
synthetic forward price — generated upstream in `sim/forward_curve.py` from
real historical spot data — plus an activity-based loading. The forward price
is itself the synthetic, forward-looking number (Law 3); this module's job is
the business-pricing step on top of it.

This module takes a forward price as a plain float, along with the customer's
Expected Annual Consumption (EAC) in kWh, the term start date, and the
fraction of that EAC expected to be unhedged ("naked") over the term. It
applies an activity-based formula covering three components:
  1. forward_price — expected wholesale cost
  2. expected_capital_cost_per_mwh — annualised cost of holding VaR collateral
     against this customer's stressed *naked* position
  3. TARGET_MARGIN_GBP_PER_MWH — flat £2/MWh target margin (additive, not %)

This module is pure: it takes inputs as plain values and returns a number.
It does not import from `sim/` — the forward price and naked fraction arrive
across the `interface/` seam as plain values, keeping the Point-in-Time
Blindfold structural and the curve-generation/hedging logic on the SIM side
where Law 3 and the hedging mandate live.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 2a pricing fix,
Phase 6c naked-fraction fix.
"""

WACC = 0.10
TARGET_MARGIN_GBP_PER_MWH = 2.00
SIGMA_STRESSED_PRE_2023 = 0.50
SIGMA_STRESSED_POST_2023 = 1.50
Z_SCORE = 1.645

# Backward-compatible default: price as if the full EAC were unhedged. Callers
# on the SIM side that know the hedging mandate's floor should pass
# naked_fraction = 1 - MIN_HEDGE_FLOOR (sim.hedging_strategy) instead.
DEFAULT_NAKED_FRACTION = 1.0


def price_fixed_tariff(
    forward_price: float, eac_kwh: int, term_start: str,
    naked_fraction: float = DEFAULT_NAKED_FRACTION,
    policy_cost_per_mwh: float = 0.0,
    network_cost_per_mwh: float = 0.0,
    profitability_uplift_per_mwh: float = 0.0,
) -> float:
    """Price a fixed unit rate (£/MWh) covering wholesale cost + capital cost + margin.

    forward_price: SYNTHETIC forward price (£/MWh) from sim.forward_curve.
    eac_kwh: customer's Expected Annual Consumption in kWh.
    term_start: ISO date string "YYYY-MM-DD" for the contract term start.
    naked_fraction: fraction of eac_kwh expected to be unhedged ("naked")
        over the term — i.e. the volume the capital-cost/VaR collateral
        charge is actually based on. Defaults to 1.0 (fully naked), matching
        the pre-Phase-6c behaviour. Under the Phase 5c minimum-hedge mandate
        (sim.hedging_strategy.MIN_HEDGE_FLOOR = 0.85), at most 15% of volume
        is ever naked, so callers should pass naked_fraction = 0.15 rather
        than pricing capital cost on 100% of EAC while only ever charging it
        on ~15%.
    policy_cost_per_mwh: RO + CfD levy pass-through (£/MWh). Zero for gas
        (RO/CfD are electricity-only obligations). Callers supply this from
        simulation.policy_costs.get_electricity_policy_cost_per_mwh().
    network_cost_per_mwh: DUoS + TNUoS pass-through (£/MWh). Phase 29a.
        Zero for gas. Callers supply from
        simulation.policy_costs.get_electricity_network_cost_per_mwh().

    profitability_uplift_per_mwh: additional margin applied when the company
        identifies a customer as net-negative in their prior term (Phase 44a).
        Computed by company.crm.customer_profitability.compute_profitability_uplift().
        Defaults to 0.0 (backward compatible with all existing callers).

    Six additive components:
      1. forward_price — expected wholesale cost per MWh.
      2. expected_capital_cost_per_mwh — cost of holding VaR collateral against
         the stressed *naked* position over the term, spread across all of
         eac_mwh (the recovery basis). Uses sigma_stressed (the regulatory
         floor: 0.50 pre-2023, 1.50 post-2023) rather than sigma_recent — pricing
         a forward contract must use the regulatory floor, not current-market
         conditions, to avoid the same zero-sigma error the hf=0.00 trap produced.
         expected_capital_cost_per_mwh = Z_SCORE x sigma_stressed x forward_price
         x WACC x naked_fraction — independent of customer size (eac_mwh
         cancels), but scaled by naked_fraction so it reflects the volume
         actually at risk under the hedging mandate.
      3. TARGET_MARGIN_GBP_PER_MWH — flat £2/MWh target margin.
      4. policy_cost_per_mwh — RO + CfD levy pass-through (Phase 21a).
      5. network_cost_per_mwh — DUoS + TNUoS pass-through (Phase 29a).
      6. profitability_uplift_per_mwh — activity-based repricing for net-negative accounts (Phase 44a).

    Returns the priced unit rate as a float (£/MWh).
    """
    sigma_stressed = SIGMA_STRESSED_POST_2023 if term_start >= "2023-01-01" else SIGMA_STRESSED_PRE_2023
    eac_mwh = eac_kwh / 1000
    naked_mwh = eac_mwh * naked_fraction
    var_stressed = Z_SCORE * sigma_stressed * naked_mwh * forward_price
    expected_capital_cost_per_mwh = (var_stressed * WACC) / eac_mwh

    return (
        forward_price
        + expected_capital_cost_per_mwh
        + TARGET_MARGIN_GBP_PER_MWH
        + policy_cost_per_mwh
        + network_cost_per_mwh
        + profitability_uplift_per_mwh
    )


# ToU multipliers applied on top of the flat rate calculated above.
# Peak covers ~30% of residential consumption; multipliers chosen so that
# a 30/70 peak/off-peak consumption split is revenue-neutral vs the flat rate.
TOU_PEAK_MULTIPLIER = 1.50
TOU_OFFPEAK_MULTIPLIER = (1.0 - 0.30 * TOU_PEAK_MULTIPLIER) / 0.70  # ≈ 0.786


def price_tou_tariff(
    forward_price: float, eac_kwh: int, term_start: str,
    naked_fraction: float = DEFAULT_NAKED_FRACTION,
) -> tuple[float, float]:
    """Price a Time-of-Use tariff for HH (smart meter) customers.

    Returns (peak_rate_gbp_per_mwh, offpeak_rate_gbp_per_mwh).

    The flat rate from price_fixed_tariff() is computed first, then split
    into peak and off-peak tiers using TOU_PEAK_MULTIPLIER / TOU_OFFPEAK_MULTIPLIER.
    Revenue-neutral at the 30/70 peak/off-peak consumption split assumption;
    actual revenue impact emerges from real HH consumption data.
    """
    flat = price_fixed_tariff(forward_price, eac_kwh, term_start, naked_fraction)
    return flat * TOU_PEAK_MULTIPLIER, flat * TOU_OFFPEAK_MULTIPLIER
