"""Pricing of fixed-rate domestic tariffs.

Synthetic Forward Curve law: a customer's fixed unit rate is derived from a
synthetic forward price — generated upstream in `sim/forward_curve.py` from
real historical spot data — plus an activity-based loading. The forward price
is itself the synthetic, forward-looking number (Law 3); this module's job is
the business-pricing step on top of it.

This module takes a forward price as a plain float, along with the customer's
Expected Annual Consumption (EAC) in kWh and the term start date. It applies
an activity-based formula covering three components:
  1. forward_price — expected wholesale cost
  2. expected_capital_cost_per_mwh — annualised cost of holding VaR collateral
     against this customer's stressed position
  3. TARGET_MARGIN_GBP_PER_MWH — flat £2/MWh target margin (additive, not %)

This module is pure: it takes inputs as plain values and returns a number.
It does not import from `sim/` — the forward price arrives across the
`interface/` seam as a plain value, keeping the Point-in-Time Blindfold
structural and the curve-generation logic on the SIM side where Law 3 lives.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 2a pricing fix.
"""

WACC = 0.10
TARGET_MARGIN_GBP_PER_MWH = 2.00
SIGMA_STRESSED_PRE_2023 = 0.50
SIGMA_STRESSED_POST_2023 = 1.50
Z_SCORE = 1.645


def price_fixed_tariff(forward_price: float, eac_kwh: int, term_start: str) -> float:
    """Price a fixed unit rate (£/MWh) covering wholesale cost + capital cost + margin.

    forward_price: SYNTHETIC forward price (£/MWh) from sim.forward_curve.
    eac_kwh: customer's Expected Annual Consumption in kWh.
    term_start: ISO date string "YYYY-MM-DD" for the contract term start.

    Three additive components:
      1. forward_price — expected wholesale cost per MWh.
      2. expected_capital_cost_per_mwh — cost of holding VaR collateral against
         the stressed position over the term. Uses sigma_stressed (the regulatory
         floor: 0.50 pre-2023, 1.50 post-2023) rather than sigma_recent — pricing
         a forward contract must use the regulatory floor, not current-market
         conditions, to avoid the same zero-sigma error the hf=0.00 trap produced.
         Note: eac_mwh cancels in the per-MWh normalisation, so
         expected_capital_cost_per_mwh = Z_SCORE x sigma_stressed x forward_price x WACC
         — independent of customer size. Every MWh sold in the same regime at the
         same price carries the same capital cost per MWh.
      3. TARGET_MARGIN_GBP_PER_MWH — flat £2/MWh target margin.

    Returns the priced unit rate as a float (£/MWh).
    """
    sigma_stressed = SIGMA_STRESSED_POST_2023 if term_start >= "2023-01-01" else SIGMA_STRESSED_PRE_2023
    eac_mwh = eac_kwh / 1000
    var_stressed = Z_SCORE * sigma_stressed * eac_mwh * forward_price
    expected_capital_cost_per_mwh = (var_stressed * WACC) / eac_mwh

    return forward_price + expected_capital_cost_per_mwh + TARGET_MARGIN_GBP_PER_MWH
