"""Pricing of fixed-rate domestic tariffs.

Synthetic Forward Curve law: a customer's fixed unit rate is derived from
real historical spot prices (the 30-day average System Sell Price ahead of
their acquisition date) plus a margin — historical spot, not invented prices.

This module is pure: it takes settlement-price records as plain dicts and
returns a number. It does not import from `sim/` — those records arrive
across the `interface/` seam, keeping the Point-in-Time Blindfold structural.
The caller is responsible for ensuring the records it passes in were knowable
*as of* the acquisition date (no peeking at the customer's own contract
period).

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 0b cross-model
delegation increment.
"""

from datetime import datetime, timedelta


def price_fixed_tariff(
    acquisition_date: str, system_price_records: list[dict], margin: float = 0.05
) -> float:
    """Price a 1-year fixed unit rate (£/MWh) for a customer acquired on
    acquisition_date.

    The rate is: (average systemSellPrice over the 30 calendar days
    immediately PRIOR to acquisition_date, i.e. the window
    [acquisition_date - 30 days, acquisition_date - 1 day] inclusive)
    multiplied by (1 + margin).

    acquisition_date is a 'YYYY-MM-DD' string. system_price_records is the
    full list of available historical records (it may contain dates outside
    the 30-day window — this function filters to the window using each
    record's "settlementDate"). Every half-hourly record in the window counts
    equally (no per-day pre-averaging). margin defaults to 0.05 (5%).

    Returns the priced unit rate as a float (£/MWh). Raises ValueError if no
    records fall within the window.
    """
    acquisition = datetime.strptime(acquisition_date, "%Y-%m-%d")
    window_start = acquisition - timedelta(days=30)
    window_end = acquisition - timedelta(days=1)

    window_records = [
        record
        for record in system_price_records
        if window_start <= datetime.strptime(record["settlementDate"], "%Y-%m-%d") <= window_end
    ]

    if not window_records:
        raise ValueError(
            f"No system price records fall within the 30-day pricing window "
            f"[{window_start:%Y-%m-%d}, {window_end:%Y-%m-%d}] before {acquisition_date}"
        )

    average_ssp = sum(r["systemSellPrice"] for r in window_records) / len(window_records)
    return average_ssp * (1 + margin)
