"""R10 CLASS GUARD for the publish-gate wedge of 2026-07-30 -> 2026-08-03.

THE DEFECT CLASS (not the instance). `tests/tools/test_billing_tab_fix.py`
asserted a literal RNG-derived date ("Account closed 2020-12-30") against the
LIVE generated customer record. The date is a draw: the W2_12/W2_13/W2_14
life-event builds legitimately moved it, the control went red, and
`process_run_complete` returned rc=1 on every cycle for ~4 days -- 401
run_complete markers queued, nothing published, while the simulation itself was
perfectly healthy. The instance was fixed by asserting structurally; this file
is what stops the CLASS coming back, per R10 ("an absurdity-class defect may NOT
be closed with an instance fix -- closure requires extending the invariant
library so the entire class fails automatically") and MAKE_IT_STICK ("convert
policy to mechanism, or accept it will evaporate").

THE RULE. A test that reads LIVE GENERATED data (site/data/**, site/state/**,
docs/reports/run_output_latest.json, the dashboard) may not assert a bare
run-derived LITERAL -- an ISO date or a generated invoice id. Those values are
outputs of the sim's RNG; pinning one turns a legitimate world change into a
publish-blocking red. Assert the value STRUCTURALLY instead (against the
record's own field, cross-checked by an independent part of the record) --
see test_billing_tab_fix.py::test_closed_account_notice_real_churned_customer_c1
for the worked example.

WHY THIS IS NARROW BY CONSTRUCTION. A guard that wedges the publish gate on a
false positive would reproduce the exact harm it exists to prevent, so it only
fires on the two shapes that actually moved (ISO dates, `C*-INV<n>` ids) and
only inside a test function that genuinely touches live generated data --
`tmp_path`/monkeypatched/inline-fixture tests are deliberately out of scope,
because a literal against a literal fixture is deterministic and safe. A
genuinely-intended pin can be registered in ALLOWED below with its reason
rather than silently disabling the guard.

R12: the generated value is a DIAGNOSTIC, never a target -- that is the same law
one level down. A control asserting a diagnostic's exact value has made it a
target.
"""
import ast
import re
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[2]
# BOTH lanes, because the class lives in both. The publish gate runs tests/ only
# and is blind to site/**, so the site lane has its own pre-commit gate -- and on
# 2026-08-03 that gate caught this very class there (a pinned live-derived
# held-credit floor, site/company/test_company_door.py), one commit after the
# tests/ instance. Guarding only the lane that happened to bite first would be an
# instance fix wearing a class fix's clothes.
SCAN_ROOTS = (PROJECT / "tests", PROJECT / "site")

# Paths whose contents are REGENERATED by a sim run (so their values are draws).
LIVE_DATA = re.compile(
    r"site/data|site/state|run_output_latest|CUSTOMERS_DIR|dashboard\.json")

# The literal shapes that actually moved: ISO dates and generated invoice ids.
#
# MONEY FIGURES ARE DELIBERATELY OUT OF SCOPE -- do not "complete" this pattern by
# adding them. Checked 2026-08-03 across tests/ and site/: every money-equality
# assertion in a live-data test function is an R15 MUTATION test that INJECTS the
# value it then asserts (e.g. test_credit_held_follows_source_r15 sets
# values_gbp=[-1000.50, -234.25, 500.00] and asserts "1,234.75" renders). Those are
# deterministic and correct. Nine such assertions would false-positive, and a guard
# that reds the gate on correct tests reproduces the exact 4-day wedge it exists to
# prevent. The one REAL money-literal offender was fixed structurally at the same
# time; if the class recurs in money form, catch it with an injected-vs-read
# distinction, not by widening this regex.
RUN_DERIVED_LITERAL = re.compile(
    r"(?<![\w-])20[12]\d-\d{2}-\d{2}(?![\w-])"   # ISO date
    r"|(?<![\w])C[\w]*-INV\d+(?![\w])"           # generated invoice id
)

# Test functions that build their own data in-process are not reading live
# output, whatever strings the surrounding module happens to contain.
SYNTHETIC_MARKERS = re.compile(r"\btmp_path\b|\bmonkeypatch\b")

# Registered exceptions: (relative path, test function name) -> why it is safe.
# Empty by design -- add an entry WITH ITS REASON rather than loosening the scan.
ALLOWED: dict = {}


def _live_data_literal_pins(tests_root: Path):
    """Return [(relpath, lineno, funcname, source_line)] for every assertion that
    pins a run-derived literal inside a live-data test function.

    Factored out so the scan itself is directly testable (R15: a control's scope
    must be inspectable, and the control must be provable on a known defect).
    """
    findings = []
    for path in sorted(tests_root.rglob("test_*.py")):
        src = path.read_text(errors="replace")
        if not LIVE_DATA.search(src):
            continue
        try:
            tree = ast.parse(src)
        except SyntaxError:
            continue
        lines = src.split("\n")
        # Report paths relative to the scan root so the scan is runnable against
        # a fixture tree (the R15 mutation tests below) as well as tests/.
        try:
            rel = path.relative_to(PROJECT).as_posix()
        except ValueError:
            rel = path.relative_to(tests_root).as_posix()
        for node in ast.walk(tree):
            if not isinstance(node, ast.FunctionDef):
                continue
            if not node.name.startswith("test_"):
                continue
            body = "\n".join(lines[node.lineno - 1: node.end_lineno])
            if not LIVE_DATA.search(body):
                continue
            if SYNTHETIC_MARKERS.search(body):
                continue  # builds its own fixture -- deterministic, not a wedge risk
            if (rel, node.name) in ALLOWED:
                continue
            for offset, line in enumerate(body.split("\n")):
                stripped = line.strip()
                if stripped.startswith("#"):
                    continue
                if not (stripped.startswith("assert") or " assert " in stripped):
                    continue
                if RUN_DERIVED_LITERAL.search(line):
                    findings.append(
                        (rel, node.lineno + offset, node.name, stripped[:160]))
    return findings


def test_no_test_pins_a_run_derived_literal_against_live_generated_data():
    """THE GUARD. A new literal pin against live sim output fails here -- at the
    author's desk -- instead of wedging the publish pipeline for four days."""
    findings = []
    for root in SCAN_ROOTS:
        if root.exists():
            findings.extend(_live_data_literal_pins(root))
    assert not findings, (
        "These assertions pin a run-derived literal (ISO date / generated invoice "
        "id) against LIVE generated data. A legitimate world change moves that "
        "value and WEDGES the publish gate -- which is exactly what happened "
        "2026-07-30..2026-08-03 (401 markers queued, nothing published). Assert "
        "the value structurally against the record's own field instead; see "
        "test_billing_tab_fix.py::test_closed_account_notice_real_churned_"
        "customer_c1. If a pin is genuinely intended, register it in ALLOWED "
        "with its reason.\n\n" + "\n".join(
            "  {}:{}  {}\n      {}".format(*f) for f in findings)
    )


def test_guard_fires_on_the_real_historical_defect(tmp_path):
    """R15 mutation proof, replaying the ACTUAL 2026-07-30 wedge.

    A control that cannot fail is worse than none. This reconstructs the exact
    assertion that wedged publishing and asserts the scan catches it -- so the
    guard's green is evidence, not decoration.
    """
    offender = tmp_path / "test_replay_of_the_wedge.py"
    offender.write_text(
        "import json\n"
        "from pathlib import Path\n"
        "CUSTOMERS_DIR = Path('site/data/customers')\n"
        "def test_closed_account_notice_real_churned_customer_c1():\n"
        "    d = json.loads((CUSTOMERS_DIR / 'C1.json').read_text())\n"
        "    notice = d['notice']\n"
        "    assert notice.startswith('Account closed 2020-12-30')\n"
    )
    findings = _live_data_literal_pins(tmp_path)
    assert len(findings) == 1, findings
    assert findings[0][2] == "test_closed_account_notice_real_churned_customer_c1"
    assert "2020-12-30" in findings[0][3]


def test_guard_fires_on_a_pinned_generated_invoice_id(tmp_path):
    """Second shape, same class: pinning `C1-INV72` breaks the moment the
    account's billing history legitimately gains or loses an invoice."""
    offender = tmp_path / "test_pinned_invoice_id.py"
    offender.write_text(
        "import json\n"
        "from pathlib import Path\n"
        "CUSTOMERS_DIR = Path('site/data/customers')\n"
        "def test_final_bill():\n"
        "    d = json.loads((CUSTOMERS_DIR / 'C1.json').read_text())\n"
        "    assert d['invoices'][-1]['id'] == 'C1-INV72'\n"
    )
    findings = _live_data_literal_pins(tmp_path)
    assert len(findings) == 1, findings
    assert "C1-INV72" in findings[0][3]


def test_guard_does_not_fire_on_a_structural_assertion(tmp_path):
    """The other half of R15 -- the guard must PASS the correct pattern, or it is
    just noise that authors learn to route around. This is the shape the real fix
    now uses: the expected value comes from the record, not a literal."""
    clean = tmp_path / "test_structural.py"
    clean.write_text(
        "import json\n"
        "from pathlib import Path\n"
        "CUSTOMERS_DIR = Path('site/data/customers')\n"
        "def test_closed_account_notice_tracks_the_record():\n"
        "    d = json.loads((CUSTOMERS_DIR / 'C1.json').read_text())\n"
        "    churn = [e for e in d['timeline'] if e['type'] == 'churned'][-1]['date']\n"
        "    assert d['notice'].startswith('Account closed ' + churn)\n"
        "    assert churn >= max(i['period_end'] for i in d['invoices'])\n"
    )
    assert _live_data_literal_pins(tmp_path) == []


def test_guard_does_not_fire_on_inline_fixture_literals(tmp_path):
    """Scope proof: a literal asserted against data the test itself constructed is
    deterministic and must not be flagged -- otherwise this guard becomes the
    false-positive that wedges the gate, reproducing the harm it prevents.

    Note the module DOES reference live data (a real pattern -- one live-data test
    sitting beside several fixture tests, e.g. test_generate_payment_ledger_data.py).
    The scoping that matters is PER FUNCTION, and this proves it: no tmp_path or
    monkeypatch marker is present to do the excluding, only the fact that this
    function's own body never touches the live path.
    """
    fixture_test = tmp_path / "test_inline_fixture.py"
    fixture_test.write_text(
        "import json\n"
        "from pathlib import Path\n"
        "CUSTOMERS_DIR = Path('site/data/customers')\n"
        "def _book_as_of(customers):\n"
        "    return max(i['issue_date'] for c in customers.values() for i in c['invoices'])\n"
        "def test_live_book_is_readable():\n"
        "    assert json.loads((CUSTOMERS_DIR / 'C1.json').read_text())['invoices']\n"
        "def test_book_as_of_is_max_issue_date():\n"
        "    customers = {'C1': {'invoices': [{'issue_date': '2021-03-31'}]}}\n"
        "    assert _book_as_of(customers) == '2021-03-31'\n"
    )
    assert _live_data_literal_pins(tmp_path) == []
