#!/usr/bin/env python3
"""R15 proof for the console instruction record (director instruction, 2026-08-19).

The mechanism exists because a console-only instruction was invisible to 381 director-facing
sources. So the mutations drive the two ways it could fail to fix that: capturing something the
director did not say, and failing to capture something he did.

The fail-closed direction is toward RAISING. Every empty or unreadable path must raise, because
an empty record is byte-indistinguishable from a director who said nothing -- which is the exact
confusion that re-parked EP6. Silence and blindness must never render the same.
"""
from __future__ import annotations

import json

import pytest

from tools import console_instruction_record as cir


def _line(role, text, ts="2026-08-19T10:00:00.000Z", blocks=None):
    content = blocks if blocks is not None else [{"type": "text", "text": text}]
    return json.dumps({"type": role, "timestamp": ts, "message": {"content": content}})


def _transcript(tmp_path, lines, name="s.jsonl"):
    d = tmp_path / "t"
    d.mkdir(exist_ok=True)
    (d / name).write_text("\n".join(lines), encoding="utf-8")
    return d


# ---------------------------------------------------------------------------
# It captures what the director said
# ---------------------------------------------------------------------------
def test_a_director_turn_is_captured_verbatim(tmp_path):
    d = _transcript(tmp_path, [_line("user", "move EP1 and EP6 to build")])
    turns = cir.director_turns(cir.newest_transcript(d))
    assert turns == [("2026-08-19T10:00:00.000Z", "move EP1 and EP6 to build")]


def test_MUTATION_the_capture_is_verbatim_and_does_NOT_expand_shorthand(tmp_path):
    """THE deliberate limit. The director writes `EP6`; the release door matches full atom ids.
    If this ever 'helpfully' expanded that to `EP6_wall_protocol_typing`, the capture would
    start GRANTING releases from a paraphrase -- inventing authority from the agent's guess at
    what he meant. The absence of expansion is the safety property, so it is pinned."""
    d = _transcript(tmp_path, [_line("user", "move EP1 and EP6 to build")])
    body = cir.render("2026-08-19", cir.director_turns(cir.newest_transcript(d)), "s.jsonl")
    assert "EP6_wall_protocol_typing" not in body.split("release door matches")[-1]
    assert "> move EP1 and EP6 to build" in body


def test_turns_are_split_by_day(tmp_path):
    d = _transcript(tmp_path, [
        _line("user", "first", ts="2026-08-18T09:00:00Z"),
        _line("user", "second", ts="2026-08-19T09:00:00Z"),
    ])
    days = cir.by_day(cir.director_turns(cir.newest_transcript(d)))
    assert sorted(days) == ["2026-08-18", "2026-08-19"]


# ---------------------------------------------------------------------------
# It does NOT capture what the director did not say
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("injected", [
    "<system-reminder>background context</system-reminder>",
    "[SYSTEM NOTIFICATION - NOT USER INPUT] a background task finished",
    "<command-name>/clear</command-name>",
    "<local-command-caveat>Caveat: the messages below were generated by the user",
    "<local-command-stdout>Auto-compact window set to auto",   # REAL leak, shipped once
    "<local-command-stderr>something went wrong",              # same family, never observed
    "Caveat: this is harness scaffolding",
])
def test_MUTATION_harness_injected_turns_are_NOT_the_director(tmp_path, injected):
    """These all arrive in the USER role and none of them is him. Capturing one would put words
    in the director's mouth in a file the release door reads -- the worst failure available
    here, and worse than capturing nothing."""
    d = _transcript(tmp_path, [_line("user", injected), _line("user", "the real instruction")])
    turns = cir.director_turns(cir.newest_transcript(d))
    assert [t for _, t in turns] == ["the real instruction"]


def test_MUTATION_tool_results_are_not_the_director(tmp_path):
    """Tool results arrive in the user role too. They are machine output; excluded by SHAPE
    rather than by sniffing their text, because their text is arbitrary."""
    d = _transcript(tmp_path, [
        _line("user", "", blocks=[{"type": "tool_result", "content": "yes, approved, unblock"}]),
        _line("user", "the real instruction"),
    ])
    assert [t for _, t in cir.director_turns(cir.newest_transcript(d))] == ["the real instruction"]


def test_assistant_turns_are_never_captured(tmp_path):
    d = _transcript(tmp_path, [
        _line("assistant", "I think we should unblock EP6_wall_protocol_typing"),
        _line("user", "no"),
    ])
    assert [t for _, t in cir.director_turns(cir.newest_transcript(d))] == ["no"]


# ---------------------------------------------------------------------------
# FAIL-CLOSED -- silence must never look like blindness
# ---------------------------------------------------------------------------
def test_MUTATION_FAIL_CLOSED_no_transcript_raises(tmp_path):
    (tmp_path / "empty").mkdir()
    with pytest.raises(cir.TranscriptUnavailable):
        cir.newest_transcript(tmp_path / "empty")


def test_MUTATION_FAIL_CLOSED_a_transcript_with_no_director_turn_raises(tmp_path):
    """The quiet one. A read that returns nothing would write an empty record, and an empty
    record says 'the director said nothing' -- which is exactly what 381 sources said about EP6
    while he had in fact spoken."""
    d = _transcript(tmp_path, [_line("assistant", "only me talking")])
    with pytest.raises(cir.TranscriptUnavailable):
        cir.director_turns(cir.newest_transcript(d))


def test_MUTATION_FAIL_CLOSED_an_unreadable_directory_raises(tmp_path):
    with pytest.raises(cir.TranscriptUnavailable):
        cir.newest_transcript(tmp_path / "does-not-exist")


def test_one_malformed_line_does_not_blind_the_read(tmp_path):
    """A single bad line is not a reason to declare the transcript empty -- that would raise on
    a healthy session and train someone to widen the except."""
    d = _transcript(tmp_path, ["{not json", _line("user", "still here")])
    assert [t for _, t in cir.director_turns(cir.newest_transcript(d))] == ["still here"]


# ---------------------------------------------------------------------------
# The written record
# ---------------------------------------------------------------------------
def test_the_record_states_that_the_director_did_not_write_it(tmp_path):
    """Provenance on its face. A file in docs/staging/ that the release door reads, containing
    the director's words but authored by the agent, must say so where a reader hits it first."""
    d = _transcript(tmp_path, [_line("user", "go ahead")])
    body = cir.render("2026-08-19", cir.director_turns(cir.newest_transcript(d)), "s.jsonl")
    assert "The director did not write or stage this file" in body
    assert "VERBATIM CAPTURE" in body


def test_writing_is_idempotent(tmp_path):
    """It runs every worker cycle. An unchanged day must not be rewritten, or the tree churns
    and every publish carries a meaningless diff."""
    d = _transcript(tmp_path, [_line("user", "go ahead")])
    staging = tmp_path / "staging"
    first = cir.write(directory=d, staging=staging)
    assert len(first) == 1
    assert cir.write(directory=d, staging=staging) == []


def test_a_new_turn_updates_the_record(tmp_path):
    d = _transcript(tmp_path, [_line("user", "go ahead")])
    staging = tmp_path / "staging"
    cir.write(directory=d, staging=staging)
    _transcript(tmp_path, [_line("user", "go ahead"), _line("user", "and one more thing")])
    assert len(cir.write(directory=d, staging=staging)) == 1
    assert "and one more thing" in (staging / "DIRECTOR_CONSOLE_2026-08-19.md").read_text()


def test_the_record_lands_where_the_release_door_looks():
    """R11, and the whole point of the mechanism: the file must be written into a directory
    `pull_forward_proposal` actually scans, or it is a diary nobody reads."""
    from background import pull_forward_proposal as pf
    assert "docs/staging" in pf.DIRECTOR_SOURCE_DIRS
    assert cir.STAGING_DIR == cir.PROJECT_DIR / "docs" / "staging"


def test_the_worker_calls_it():
    """The no-caller class. `resource_headroom` sat unwired for nine days after being built for
    a real outage; this is built for one too."""
    import inspect
    from background import background_worker
    src = inspect.getsource(background_worker.main)
    assert "console_instruction_record" in src, (
        "the console recorder is not called by the worker loop -- the director's words will "
        "stop reaching disk and nothing will say so"
    )


# ---------------------------------------------------------------------------
# The turn he typed BETWEEN turns (2026-08-25)
# ---------------------------------------------------------------------------
def _queued(text, ts="2026-08-25T16:54:41.891Z", operation="enqueue"):
    """A message sent while a turn was already running. The harness does not write it as a
    `user` record at all -- it queues it, and the transcript holds
    `{"type": "queue-operation", "operation": "enqueue", "content": "..."}`."""
    return json.dumps({"type": "queue-operation", "operation": operation,
                       "timestamp": ts, "content": text})


def test_a_message_typed_WHILE_A_TURN_IS_RUNNING_is_still_captured(tmp_path):
    """THE HOLE THIS MODULE WAS BUILT TO CLOSE, ONE CHANNEL OVER, found the day it bit.

    On 2026-08-25 the director sent a standing mandate mid-turn -- the instruction that created
    the delivery seat, and the most consequential of that day. It was QUEUED rather than written
    as a `user` record, this capture read `type == "user"` only, and so the module whose entire
    purpose is to stop his words evaporating reported eight turns, a clean run, and left no trace
    of the ninth. That is the EP6 failure exactly: the mechanism behaved perfectly and the input
    never reached the file.

    MUTATION (must fire): read `type == "user"` only.
    """
    d = _transcript(tmp_path, [
        _line("user", "a turn typed normally", ts="2026-08-25T10:00:00.000Z"),
        _queued("an architectural gap I want you to close"),
    ])

    turns = cir.director_turns(cir.newest_transcript(d))

    assert [t[1] for t in turns] == ["a turn typed normally",
                                     "an architectural gap I want you to close"]


def test_the_queued_message_is_recorded_ONCE_not_three_times(tmp_path):
    """`enqueue` and `remove` carry the SAME content -- queued, then dequeued when delivered --
    and a queued message that later lands as a real `user` record would make three. Deduped by
    text, first occurrence winning, so the recorded timestamp is when he SENT it rather than when
    the machine got round to it.

    MUTATION (must fire): drop the dedupe, or key it on uuid instead of text.
    """
    d = _transcript(tmp_path, [
        _queued("do the thing", ts="2026-08-25T16:54:41.891Z"),
        _queued("do the thing", ts="2026-08-25T16:54:59.332Z", operation="remove"),
        _line("user", "do the thing", ts="2026-08-25T17:10:00.000Z"),
    ])

    turns = cir.director_turns(cir.newest_transcript(d))

    assert turns == [("2026-08-25T16:54:41.891Z", "do the thing")]


def test_harness_scaffolding_is_STILL_not_the_director_when_it_arrives_queued(tmp_path):
    """The queued path must not become a way round the prefix filter -- otherwise widening the
    capture would have widened what counts as his word, in a file the release door reads."""
    d = _transcript(tmp_path, [
        _line("user", "a real turn", ts="2026-08-25T09:00:00.000Z"),
        _queued("<system-reminder>not him</system-reminder>"),
        _queued("<local-command-stdout>Compacted", ts="2026-08-25T16:55:00.000Z"),
    ])

    assert [t[1] for t in cir.director_turns(cir.newest_transcript(d))] == ["a real turn"]


# ---------------------------------------------------------------------------
# One day, more than one session (2026-08-25)
# ---------------------------------------------------------------------------
def test_a_SECOND_session_on_the_same_day_does_not_ERASE_the_first(tmp_path):
    """THIS MODULE'S OWN FOUNDING FAILURE, WITH THE SIGN FLIPPED, found while landing the queued
    -turn fix. `write()` regenerates one record PER CALENDAR DAY, and it built that record from a
    SINGLE transcript -- so running it from session B rewrote the day's record that session A had
    built, and session A's turns were simply gone. Which session's words survived was decided by
    which one happened to run last.

    It exists because the director's words evaporated when the pane scrolled. It was deleting them
    when a second session ran.

    MUTATION (must fire): read only `newest_transcript`.
    """
    d = tmp_path / "t"
    d.mkdir()
    (d / "a.jsonl").write_text(_line("user", "said in session A", ts="2026-08-24T09:00:00.000Z"),
                               encoding="utf-8")
    (d / "b.jsonl").write_text(_line("user", "said in session B", ts="2026-08-24T18:00:00.000Z"),
                               encoding="utf-8")
    out = tmp_path / "staging"

    cir.write(directory=d, staging=out)
    body = (out / "DIRECTOR_CONSOLE_2026-08-24.md").read_text(encoding="utf-8")

    assert "said in session A" in body, "the earlier session's turns were erased by the later one"
    assert "said in session B" in body
    assert "a.jsonl" in body and "b.jsonl" in body, (
        "the record must name every transcript it drew from, or a reader cannot tell what it saw"
    )


def test_the_same_instruction_seen_in_TWO_sessions_is_recorded_ONCE(tmp_path):
    """A resumed session replays context, so the same turn legitimately appears in two
    transcripts. Recording it twice would read as the director having said it twice."""
    d = tmp_path / "t"
    d.mkdir()
    for name, ts in (("a.jsonl", "2026-08-24T09:00:00.000Z"),
                     ("b.jsonl", "2026-08-24T11:00:00.000Z")):
        (d / name).write_text(_line("user", "do the thing", ts=ts), encoding="utf-8")

    turns, used = cir.director_turns_across(cir.recent_transcripts(d))

    assert turns == [("2026-08-24T09:00:00.000Z", "do the thing")], (
        "the earliest sighting must win, so the recorded time is when he SENT it"
    )
    assert used == ["a.jsonl", "b.jsonl"]


def test_a_session_he_never_spoke_in_is_SKIPPED_and_does_not_blind_the_read(tmp_path):
    """A transcript with no director turn is a session he was silent in, not a broken read. Only
    an EMPTY merge is a failure -- silence and blindness must never render the same, which is the
    property this whole module was built on."""
    d = tmp_path / "t"
    d.mkdir()
    (d / "quiet.jsonl").write_text(_line("assistant", "just me talking"), encoding="utf-8")
    (d / "loud.jsonl").write_text(_line("user", "a real turn", ts="2026-08-24T09:00:00.000Z"),
                                  encoding="utf-8")

    turns, used = cir.director_turns_across(cir.recent_transcripts(d))

    assert [t[1] for t in turns] == ["a real turn"]
    assert used == ["loud.jsonl"]


def test_an_ENTIRELY_silent_window_RAISES_rather_than_writing_an_empty_record(tmp_path):
    d = tmp_path / "t"
    d.mkdir()
    (d / "quiet.jsonl").write_text(_line("assistant", "just me talking"), encoding="utf-8")

    with pytest.raises(cir.TranscriptUnavailable):
        cir.director_turns_across(cir.recent_transcripts(d))


def test_an_ARCHIVED_days_record_is_updated_IN_PLACE_and_never_resurrected(tmp_path):
    """A DOORBELL FOR A TURN ACTIONED DAYS AGO (2026-08-25). Merging across a multi-day window
    means most of those days have already been read, actioned and archived to `done/`. Writing
    their record back into the staging ROOT rings the doorbell again -- and leaves the same
    document in two rooms making mutually exclusive claims, which `background/finding_classes.py`
    refuses by name (it did, the moment this landed).

    An archived day's record still gets RICHER as more transcripts merge into it. It just does
    not come back to life.

    MUTATION (must fire): always write to the staging root.
    """
    d = _transcript(tmp_path, [
        _line("user", "said on the 22nd", ts="2026-08-22T09:00:00.000Z"),
        _line("user", "said today", ts="2026-08-25T09:00:00.000Z"),
    ])
    out = tmp_path / "staging"
    (out / "done").mkdir(parents=True)
    archived = out / "done" / "DIRECTOR_CONSOLE_2026-08-22.md"
    archived.write_text("an older, thinner record\n", encoding="utf-8")

    cir.write(directory=d, staging=out)

    assert "said on the 22nd" in archived.read_text(encoding="utf-8"), (
        "the archived record was not updated, so merging gained nothing for that day"
    )
    assert not (out / "DIRECTOR_CONSOLE_2026-08-22.md").exists(), (
        "an actioned day's record was re-created in the staging root -- that is a doorbell for a "
        "turn already handled, and the same document in two rooms"
    )
    assert (out / "DIRECTOR_CONSOLE_2026-08-25.md").is_file(), (
        "a day with no archived copy must still land in the root, where the doorbell reads it"
    )
