#!/usr/bin/env python3
"""R15 proof for the console instruction record (director instruction, 2026-08-19).

The mechanism exists because a console-only instruction was invisible to 381 director-facing
sources. So the mutations drive the two ways it could fail to fix that: capturing something the
director did not say, and failing to capture something he did.

The fail-closed direction is toward RAISING. Every empty or unreadable path must raise, because
an empty record is byte-indistinguishable from a director who said nothing -- which is the exact
confusion that re-parked EP6. Silence and blindness must never render the same.
"""
from __future__ import annotations

import json

import pytest

from tools import console_instruction_record as cir


def _line(role, text, ts="2026-08-19T10:00:00.000Z", blocks=None):
    content = blocks if blocks is not None else [{"type": "text", "text": text}]
    return json.dumps({"type": role, "timestamp": ts, "message": {"content": content}})


def _transcript(tmp_path, lines, name="s.jsonl"):
    d = tmp_path / "t"
    d.mkdir(exist_ok=True)
    (d / name).write_text("\n".join(lines), encoding="utf-8")
    return d


# ---------------------------------------------------------------------------
# It captures what the director said
# ---------------------------------------------------------------------------
def test_a_director_turn_is_captured_verbatim(tmp_path):
    d = _transcript(tmp_path, [_line("user", "move EP1 and EP6 to build")])
    turns = cir.director_turns(cir.newest_transcript(d))
    assert turns == [("2026-08-19T10:00:00.000Z", "move EP1 and EP6 to build")]


def test_MUTATION_the_capture_is_verbatim_and_does_NOT_expand_shorthand(tmp_path):
    """THE deliberate limit. The director writes `EP6`; the release door matches full atom ids.
    If this ever 'helpfully' expanded that to `EP6_wall_protocol_typing`, the capture would
    start GRANTING releases from a paraphrase -- inventing authority from the agent's guess at
    what he meant. The absence of expansion is the safety property, so it is pinned."""
    d = _transcript(tmp_path, [_line("user", "move EP1 and EP6 to build")])
    body = cir.render("2026-08-19", cir.director_turns(cir.newest_transcript(d)), "s.jsonl")
    assert "EP6_wall_protocol_typing" not in body.split("release door matches")[-1]
    assert "> move EP1 and EP6 to build" in body


def test_turns_are_split_by_day(tmp_path):
    d = _transcript(tmp_path, [
        _line("user", "first", ts="2026-08-18T09:00:00Z"),
        _line("user", "second", ts="2026-08-19T09:00:00Z"),
    ])
    days = cir.by_day(cir.director_turns(cir.newest_transcript(d)))
    assert sorted(days) == ["2026-08-18", "2026-08-19"]


# ---------------------------------------------------------------------------
# It does NOT capture what the director did not say
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("injected", [
    "<system-reminder>background context</system-reminder>",
    "[SYSTEM NOTIFICATION - NOT USER INPUT] a background task finished",
    "<command-name>/clear</command-name>",
    "<local-command-caveat>Caveat: the messages below were generated by the user",
    "<local-command-stdout>Auto-compact window set to auto",   # REAL leak, shipped once
    "<local-command-stderr>something went wrong",              # same family, never observed
    "Caveat: this is harness scaffolding",
])
def test_MUTATION_harness_injected_turns_are_NOT_the_director(tmp_path, injected):
    """These all arrive in the USER role and none of them is him. Capturing one would put words
    in the director's mouth in a file the release door reads -- the worst failure available
    here, and worse than capturing nothing."""
    d = _transcript(tmp_path, [_line("user", injected), _line("user", "the real instruction")])
    turns = cir.director_turns(cir.newest_transcript(d))
    assert [t for _, t in turns] == ["the real instruction"]


def test_MUTATION_tool_results_are_not_the_director(tmp_path):
    """Tool results arrive in the user role too. They are machine output; excluded by SHAPE
    rather than by sniffing their text, because their text is arbitrary."""
    d = _transcript(tmp_path, [
        _line("user", "", blocks=[{"type": "tool_result", "content": "yes, approved, unblock"}]),
        _line("user", "the real instruction"),
    ])
    assert [t for _, t in cir.director_turns(cir.newest_transcript(d))] == ["the real instruction"]


def test_assistant_turns_are_never_captured(tmp_path):
    d = _transcript(tmp_path, [
        _line("assistant", "I think we should unblock EP6_wall_protocol_typing"),
        _line("user", "no"),
    ])
    assert [t for _, t in cir.director_turns(cir.newest_transcript(d))] == ["no"]


# ---------------------------------------------------------------------------
# FAIL-CLOSED -- silence must never look like blindness
# ---------------------------------------------------------------------------
def test_MUTATION_FAIL_CLOSED_no_transcript_raises(tmp_path):
    (tmp_path / "empty").mkdir()
    with pytest.raises(cir.TranscriptUnavailable):
        cir.newest_transcript(tmp_path / "empty")


def test_MUTATION_FAIL_CLOSED_a_transcript_with_no_director_turn_raises(tmp_path):
    """The quiet one. A read that returns nothing would write an empty record, and an empty
    record says 'the director said nothing' -- which is exactly what 381 sources said about EP6
    while he had in fact spoken."""
    d = _transcript(tmp_path, [_line("assistant", "only me talking")])
    with pytest.raises(cir.TranscriptUnavailable):
        cir.director_turns(cir.newest_transcript(d))


def test_MUTATION_FAIL_CLOSED_an_unreadable_directory_raises(tmp_path):
    with pytest.raises(cir.TranscriptUnavailable):
        cir.newest_transcript(tmp_path / "does-not-exist")


def test_one_malformed_line_does_not_blind_the_read(tmp_path):
    """A single bad line is not a reason to declare the transcript empty -- that would raise on
    a healthy session and train someone to widen the except."""
    d = _transcript(tmp_path, ["{not json", _line("user", "still here")])
    assert [t for _, t in cir.director_turns(cir.newest_transcript(d))] == ["still here"]


# ---------------------------------------------------------------------------
# The written record
# ---------------------------------------------------------------------------
def test_the_record_states_that_the_director_did_not_write_it(tmp_path):
    """Provenance on its face. A file in docs/staging/ that the release door reads, containing
    the director's words but authored by the agent, must say so where a reader hits it first."""
    d = _transcript(tmp_path, [_line("user", "go ahead")])
    body = cir.render("2026-08-19", cir.director_turns(cir.newest_transcript(d)), "s.jsonl")
    assert "The director did not write or stage this file" in body
    assert "VERBATIM CAPTURE" in body


def test_writing_is_idempotent(tmp_path):
    """It runs every worker cycle. An unchanged day must not be rewritten, or the tree churns
    and every publish carries a meaningless diff."""
    d = _transcript(tmp_path, [_line("user", "go ahead")])
    staging = tmp_path / "staging"
    first = cir.write(directory=d, staging=staging)
    assert len(first) == 1
    assert cir.write(directory=d, staging=staging) == []


def test_a_new_turn_updates_the_record(tmp_path):
    d = _transcript(tmp_path, [_line("user", "go ahead")])
    staging = tmp_path / "staging"
    cir.write(directory=d, staging=staging)
    _transcript(tmp_path, [_line("user", "go ahead"), _line("user", "and one more thing")])
    assert len(cir.write(directory=d, staging=staging)) == 1
    assert "and one more thing" in (staging / "DIRECTOR_CONSOLE_2026-08-19.md").read_text()


def test_the_record_lands_where_the_release_door_looks():
    """R11, and the whole point of the mechanism: the file must be written into a directory
    `pull_forward_proposal` actually scans, or it is a diary nobody reads."""
    from background import pull_forward_proposal as pf
    assert "docs/staging" in pf.DIRECTOR_SOURCE_DIRS
    assert cir.STAGING_DIR == cir.PROJECT_DIR / "docs" / "staging"


def test_the_worker_calls_it():
    """The no-caller class. `resource_headroom` sat unwired for nine days after being built for
    a real outage; this is built for one too."""
    import inspect
    from background import background_worker
    src = inspect.getsource(background_worker.main)
    assert "console_instruction_record" in src, (
        "the console recorder is not called by the worker loop -- the director's words will "
        "stop reaching disk and nothing will say so"
    )
