"""Generation of synthetic forward prices for fixed-rate domestic tariffs.

Synthetic Forward Curve law: no real UK forward-curve data exists for this
purpose, so a forward price is built FROM real historical spot data — the
Historical Ground Truth law stays satisfied because the base is always real
spot, never invented. The output is a SYNTHETIC number and must be labelled
as such wherever it is used downstream (it is the input `saas/tariff_pricing`
applies its margin to, not a real market quote).

A forward price for a fixed-rate contract starting on `acquisition_date` has
three components, each a configurable parameter per the Master Backlog:
  1. base — the arithmetic mean System Sell Price over the `lookback_days`
     days immediately before acquisition_date (real spot, rolling-average)
  2. volatility premium — the population standard deviation (sigma) of SSP
     over that same window, scaled by `risk_factor`, added to the base. This
     is what makes the price forward-looking rather than a flat spot average:
     it loads in a margin for the price uncertainty actually observed in the
     run-up to the contract.
  3. seasonal adjustment — a fixed-rate contract delivers across
     `contract_length_months` months, not just the month it's sold in, so the
     per-month winter/summer multipliers are blended (averaged) across every
     month the contract will span before being applied.

This is the primary fix for the systematic losses Phase 0c found: a fixed
tariff priced off a simple 30-day backward-looking spot average chronically
under-priced relative to the wholesale cost actually incurred across a full
year (every 2016 customer ran at a loss, portfolio margin -£78.28). Loading
in a volatility premium and a seasonal view of the whole delivery period is
how a real forward desk would price this risk; this module does the same
thing synthetically, from real historical spot as its only real-world input.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 1c increment.
"""

import statistics
from datetime import date, timedelta

WINTER_MONTHS = {10, 11, 12, 1, 2, 3}
WINTER_MULTIPLIER = 1.15
SUMMER_MULTIPLIER = 0.95

def generate_forward_price(acquisition_date: str, system_price_records: list[dict],
                           contract_length_months: int = 12,
                           lookback_days: int = 90,
                           risk_factor: float = 1.2) -> float:
    # Convert acquisition date to a date object
    start_date = date.fromisoformat(acquisition_date)

    # Define the lookback window dates
    end_lookback_date = start_date - timedelta(days=1)
    start_lookback_date = start_date - timedelta(days=lookback_days)

    # Filter records within the lookback window
    filtered_records = [
        record for record in system_price_records
        if date.fromisoformat(record['settlementDate']) >= start_lookback_date and
           date.fromisoformat(record['settlementDate']) <= end_lookback_date
    ]

    # Raise ValueError if no records are found within the lookback window
    if not filtered_records:
        raise ValueError(f"No price records found in the lookback window [{start_lookback_date}, {end_lookback_date}] for acquisition date {acquisition_date}.")

    # Calculate base price: arithmetic mean of systemSellPrice
    base_price = statistics.mean(record['systemSellPrice'] for record in filtered_records)

    # Calculate volatility premium: population standard deviation * risk factor
    volatility_premium = statistics.pstdev(record['systemSellPrice'] for record in filtered_records) * risk_factor

    # Calculate forward base price with volatility premium
    forward_base = base_price + volatility_premium

    # Determine the start month and calculate seasonal multipliers for the contract length
    start_month = start_date.month
    seasonal_multipliers = []

    for offset in range(contract_length_months):
        current_month = (start_month - 1 + offset) % 12 + 1
        if current_month in WINTER_MONTHS:
            seasonal_multipliers.append(WINTER_MULTIPLIER)
        else:
            seasonal_multipliers.append(SUMMER_MULTIPLIER)

    # Calculate overall seasonal multiplier as the arithmetic mean of monthly multipliers
    seasonal_multiplier = statistics.mean(seasonal_multipliers)

    # Calculate final forward price with seasonal adjustment
    forward_price = forward_base * seasonal_multiplier

    return forward_price
