"""Hedging strategy — the agent's decision and evolution logic.

Phase 1d does not test pre-set strategies; it builds an agent that decides
its own hedge position and evolves it over time, using only information it
could actually have at each decision point (the Point-in-Time Blindfold
applies to strategy reasoning, not just to data).

The agent controls exactly one lever: hedge_fraction — the proportion
(0.0-1.0) of a contract term's expected volume it locks in ahead of time at
the forward price available on that term's start date (the "annual strip"
instrument — see simulation/run_phase1d.py for why tenor is held fixed at
the 12-month contract length rather than varied). The remainder is bought at
spot as it's delivered. hedge_fraction=0.0 is fully naked, 1.0 is fully
hedged.

Two decisions live here:

1. decide_initial_hedge_fraction — what does a brand-new entrant with no
   track record do on day one? It has a forward curve to look at but no
   history of its own outcomes to learn from, so it adopts a deliberately
   neutral starting prior: hedge half the book, leave half exposed. This is
   the textbook "no information" starting point — confidently committing to
   either extreme (fully naked or fully hedged) on day one would be a bet,
   not a strategy; 50/50 is the only position that isn't already a guess
   about which way prices will move.

2. evolve_hedge_fraction — once a contract term completes, its outcomes are
   now history the agent can learn from (and only then — no looking ahead
   into the next term, which hasn't happened yet). The agent compares what
   actually happened (its chosen hedge_fraction's realised margin) against
   what would have happened had it stayed fully naked for that exact same
   term (same consumption, same real spot prices, same fixed-tariff
   revenue — the only thing that differs is how the wholesale side was
   sourced). That comparison is the cleanest possible PiT-safe signal:
   - If the hedge produced MORE margin than naked would have, locking in
     ahead of delivery protected the book from spot prices that ended up
     running hot — so the agent leans further into hedging next time
     (raise hedge_fraction).
   - If the hedge produced LESS margin than naked would have, the locked-in
     price turned out to be a worse deal than just buying at spot as it
     came — so the agent backs off (lower hedge_fraction).
   - If the two are within a small tolerance of each other, the difference
     is noise rather than signal, and changing course on noise is how
     strategies end up thrashing — so the agent holds its position.
   Each adjustment moves by one fixed step and is clamped to [0.0, 1.0] —
   deliberately small, bounded, gradual evolution rather than over-reacting
   to any single year's result.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 1d hedging
increment.
"""

INITIAL_HEDGE_FRACTION = 0.5       # no track record yet — neutral 50/50 starting prior
EVOLUTION_STEP = 0.1               # bounded, gradual adjustment per completed contract term
MARGIN_TOLERANCE_GBP = 5.0         # treat a difference smaller than this as noise, not signal


def decide_initial_hedge_fraction() -> tuple[float, str]:
    """The agent's day-one decision, before it has any track record of its
    own outcomes to learn from.

    Returns (hedge_fraction, reasoning) — INITIAL_HEDGE_FRACTION and a short
    plain-English explanation of why that starting point was chosen (for
    the audit trail this phase's gate review depends on). The reasoning
    text should explain: with no history yet, committing fully to either
    extreme would be a directional bet on prices, not a grounded strategy —
    so the agent starts at the neutral midpoint and lets its own observed
    results (not a guess) drive it from there.
    """
    reasoning = "With no track record, committing fully to either extreme (fully hedged or fully naked) would be a directional bet on prices. Starting at 50/50 allows the agent to learn from its own outcomes without making an initial assumption."
    return INITIAL_HEDGE_FRACTION, reasoning


def evolve_hedge_fraction(current_hedge_fraction: float, naked_margin_gbp: float, actual_margin_gbp: float) -> tuple[float, str]:
    """Adjust the hedge_fraction for the NEXT contract term, based only on
    what just happened in the term that has now completed.

    naked_margin_gbp is the hypothetical margin the SAME completed term
    would have produced at hedge_fraction=0.0 (100% spot exposure) — same
    consumption, same real spot prices, same fixed-tariff revenue, the only
    difference being how the wholesale side was sourced. actual_margin_gbp
    is what the term actually produced at current_hedge_fraction. Comparing
    the two isolates exactly what the hedge itself contributed (or cost),
    with no foresight involved — both figures come from a term that has
    already fully played out.

    Decision rule:
      difference = actual_margin_gbp - naked_margin_gbp
      - if difference > MARGIN_TOLERANCE_GBP: the hedge beat naked by a
        meaningful margin — raise hedge_fraction by EVOLUTION_STEP, capped
        at 1.0 ("lean further into what just worked")
      - if difference < -MARGIN_TOLERANCE_GBP: the hedge underperformed
        naked by a meaningful margin — lower hedge_fraction by
        EVOLUTION_STEP, floored at 0.0 ("back off from what just cost
        money")
      - otherwise (the difference is within +/- MARGIN_TOLERANCE_GBP): hold
        — the difference is noise, not signal, so the position is left
        unchanged

    Returns (new_hedge_fraction, reasoning) — the adjusted (or unchanged)
    hedge_fraction, and a short plain-English explanation that names the
    actual numbers involved (naked_margin_gbp, actual_margin_gbp, the
    difference, and the resulting new_hedge_fraction) so each step of the
    evolution is independently auditable from the printed log alone.
    """
    difference = actual_margin_gbp - naked_margin_gbp

    if difference > MARGIN_TOLERANCE_GBP:
        new_hedge_fraction = min(1.0, current_hedge_fraction + EVOLUTION_STEP)
        reasoning = (f"Actual margin: £{actual_margin_gbp:.2f}, Naked margin: £{naked_margin_gbp:.2f}, Difference: £{difference:.2f}. The hedge beat naked by a meaningful margin, so the agent is leaning further into hedging with new hedge fraction: {new_hedge_fraction:.2f}")
    elif difference < -MARGIN_TOLERANCE_GBP:
        new_hedge_fraction = max(0.0, current_hedge_fraction - EVOLUTION_STEP)
        reasoning = (f"Actual margin: £{actual_margin_gbp:.2f}, Naked margin: £{naked_margin_gbp:.2f}, Difference: £{difference:.2f}. The hedge underperformed naked by a meaningful margin, so the agent is backing off with new hedge fraction: {new_hedge_fraction:.2f}")
    else:
        new_hedge_fraction = current_hedge_fraction
        reasoning = (f"Actual margin: £{actual_margin_gbp:.2f}, Naked margin: £{naked_margin_gbp:.2f}, Difference: £{difference:.2f}. The difference is within tolerance (noise, not signal), so the position is held unchanged with hedge fraction: {new_hedge_fraction:.2f}")

    return new_hedge_fraction, reasoning
