"""Hedge book economics — pure per-settlement-period hedge calculations.

Models what it actually costs a supplier to back a fixed-rate tariff with
energy supply contracts, rather than the simplified "buy everything at spot"
assumption every prior phase has used. Given a customer's actual consumption
in one settlement period, a hedge_fraction (the proportion of that volume
locked in ahead of delivery at a forward price, with the remainder bought at
spot as it's delivered), this computes that period's hedged volume, unhedged
volume, revenue, wholesale cost, and margin.

Phase 1d does not hand the agent a menu of pre-set strategies to compare —
it gives the agent one configurable lever (hedge_fraction, the % of volume
locked in via the chosen instrument) and lets it set and evolve that lever
itself, term by term, based only on what it has actually observed
(simulation/run_phase1d.py and sim/hedging_strategy.py own that reasoning;
this module only knows how to price a position once chosen). hedge_fraction
of 0.0 is fully naked (100% spot exposure — the implicit baseline every
prior phase has modelled), 1.0 is fully hedged, and anything between is a
blend — this single function is generic over whatever value the agent
arrives at, and over whichever instrument supplied hedge_price_gbp_per_mwh.

hedge_price IS a synthetic forward price (Law 3) — exactly the kind of
number sim.forward_curve.generate_forward_price produces and that
saas.tariff_pricing.price_fixed_tariff prices the customer's tariff from.
Using that same kind of number as the hedge price keeps "what a forward desk
would actually lock in to cover this customer" internally consistent end to
end: the number that sets what the customer pays is the number the supplier
could have paid to cover it.

This module is pure (Phase 1d constraint: "hedge book lives in SIM side") —
it takes plain numeric values and returns plain numeric values, with no
imports from saas/ or simulation/. The orchestration layer is responsible
for supplying the fixed tariff rate and the hedge price as plain floats,
exactly as saas.tariff_pricing receives its forward price as a plain float
across the interface/ seam.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 1d hedging
increment.
"""


def settle_hedged_period(consumption_kwh: float, fixed_tariff_rate_gbp_per_mwh: float, hedge_price_gbp_per_mwh: float, hedge_fraction: float, spot_price_gbp_per_mwh: float) -> dict:
    """Compute the hedge-aware revenue, cost, and margin for one customer's
    one settlement period.

    consumption_kwh is the actual delivered volume for this period (Phase 1d
    assumes EAC is realised exactly — volume risk is a later phase's
    concern). hedge_fraction (0.0-1.0) splits that volume into a hedged
    portion (bought ahead at hedge_price_gbp_per_mwh — the forward price
    locked in at the contract term's start date) and an unhedged portion
    (bought at spot_price_gbp_per_mwh, the real System Sell Price for this
    exact settlement period). fixed_tariff_rate_gbp_per_mwh is the
    customer's contracted unit rate — what they pay regardless of how the
    supplier sources the energy behind it.

    Computed as (converting kWh to MWh by /1000):
      hedged_volume_kwh = hedge_fraction * consumption_kwh
      unhedged_volume_kwh = consumption_kwh - hedged_volume_kwh
      revenue_gbp = consumption_kwh / 1000 * fixed_tariff_rate_gbp_per_mwh
      wholesale_cost_gbp = (hedged_volume_kwh / 1000 * hedge_price_gbp_per_mwh
                            + unhedged_volume_kwh / 1000 * spot_price_gbp_per_mwh)
      margin_gbp = revenue_gbp - wholesale_cost_gbp

    Returns {hedged_volume_kwh, unhedged_volume_kwh, revenue_gbp,
    wholesale_cost_gbp, margin_gbp}.
    """
    hedged_volume_kwh = hedge_fraction * consumption_kwh
    unhedged_volume_kwh = consumption_kwh - hedged_volume_kwh
    revenue_gbp = consumption_kwh / 1000 * fixed_tariff_rate_gbp_per_mwh
    wholesale_cost_gbp = (hedged_volume_kwh / 1000 * hedge_price_gbp_per_mwh +
                          unhedged_volume_kwh / 1000 * spot_price_gbp_per_mwh)
    margin_gbp = revenue_gbp - wholesale_cost_gbp

    return {
        'hedged_volume_kwh': hedged_volume_kwh,
        'unhedged_volume_kwh': unhedged_volume_kwh,
        'revenue_gbp': revenue_gbp,
        'wholesale_cost_gbp': wholesale_cost_gbp,
        'margin_gbp': margin_gbp
    }
