"""Phase 3b — merit-order wholesale price model (Regime 2/3 physics engine).

This is the first synthetic *price* physics engine: a structural model of
how the System Sell Price emerges from gas, demand, and renewable supply,
rather than a re-sampling of historical SSP itself. Before this engine can
be trusted for forward projection (Regime 3), it must be validated against
9 years of real Elexon SSP — see docs/calibration/price-engine.md for the
calibration report and `simulation/run_phase3b_calibration.py` for the
comparison run. Until that gate clears, every simulation phase continues to
use real historical SSP (sim/system_prices_history.py), not this engine.

Three pieces, per the MASTER_BACKLOG Phase 3b spec:

1. Gas floor — the marginal cost of the price-setting gas plant:
     P_gas_floor = gas_price / thermal_efficiency
   A CCGT burning gas at `gas_price` £/MWh(th) with `thermal_efficiency`
   (MWh(e) per MWh(th)) needs `gas_price / thermal_efficiency` £ of gas per
   MWh(e) generated — its floor price, below which it would run at a loss.

2. System margin shape — how tight the supply/demand margin pushes price
   above that floor:
     P_HH = P_gas_floor * (demand / renewable_generation) ^ gamma
   When renewables are abundant relative to demand, the ratio (and hence
   price) falls toward (and can dip below, with gamma close to the floor
   if renewables exceed demand) the gas floor; when the margin is tight
   (demand >> renewables), price rises supralinearly. `gamma` (1.5-2.5)
   controls how sharply price responds to margin tightness — a real
   merit-order curve is convex, not linear.

3. Wind cubic physics — converts a wind speed into a fraction of a turbine's
   rated output, the standard idealised turbine power curve:
     - cut-in:  v <  3 m/s -> 0
     - ramp:    3 <= v <= 12 m/s -> cubic ramp, P proportional to v^3
     - rated:   12 < v <= 25 m/s -> 1.0 (rated output)
     - cut-out: v > 25 m/s -> 0 (storm shutdown, blades feathered)

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 3b increment.
"""

THERMAL_EFFICIENCY = 0.50  # MWh(e) per MWh(th), starting assumption per spec

GAMMA_MIN = 1.5
GAMMA_MAX = 2.5

WIND_CUT_IN_MS = 3.0
WIND_RATED_MS = 12.0
WIND_CUT_OUT_MS = 25.0


def gas_floor_price(gas_price_gbp_per_mwh: float, thermal_efficiency: float = THERMAL_EFFICIENCY) -> float:
    """The marginal cost (£/MWh(e)) of gas-fired generation at gas_price.

    P_gas_floor = gas_price / thermal_efficiency
    """
    return gas_price_gbp_per_mwh / thermal_efficiency


def system_margin_price(
    gas_floor_price_gbp_per_mwh: float,
    demand_mw: float,
    renewable_generation_mw: float,
    gamma: float,
) -> float:
    """The merit-order system price (£/MWh): the gas floor scaled by how
    tight the demand/renewable-supply margin is.

    P_HH = P_gas_floor * (demand / renewable_generation) ^ gamma

    gamma must be in [GAMMA_MIN, GAMMA_MAX] (1.5-2.5) per the Phase 3b spec
    — it is a calibrated parameter, not a free input. renewable_generation_mw
    must be > 0 (a zero-renewables period is a divide-by-zero in this simple
    ratio form; callers should floor it at some small epsilon if real data
    contains exact zeros).
    """
    if not (GAMMA_MIN <= gamma <= GAMMA_MAX):
        raise ValueError(
            f"gamma must be in [{GAMMA_MIN}, {GAMMA_MAX}], got {gamma}"
        )
    if renewable_generation_mw <= 0:
        raise ValueError("renewable_generation_mw must be > 0")

    return gas_floor_price_gbp_per_mwh * (demand_mw / renewable_generation_mw) ** gamma


def wind_power_output_fraction(wind_speed_ms: float, rated_power_mw: float = 1.0) -> float:
    """Idealised turbine power curve: fraction of rated_power_mw delivered
    at wind_speed_ms.

    - < 3 m/s (cut-in): 0
    - 3-12 m/s: cubic ramp, P proportional to v^3, continuous from 0 at
      3 m/s to rated_power_mw at 12 m/s
    - 12-25 m/s (rated): rated_power_mw
    - > 25 m/s (cut-out): 0
    """
    if wind_speed_ms < WIND_CUT_IN_MS or wind_speed_ms > WIND_CUT_OUT_MS:
        return 0.0
    if wind_speed_ms <= WIND_RATED_MS:
        ramp_fraction = (wind_speed_ms ** 3 - WIND_CUT_IN_MS ** 3) / (
            WIND_RATED_MS ** 3 - WIND_CUT_IN_MS ** 3
        )
        return ramp_fraction * rated_power_mw
    return rated_power_mw


def synthetic_price(
    gas_price_gbp_per_mwh: float,
    demand_mw: float,
    renewable_generation_mw: float,
    gamma: float,
    thermal_efficiency: float = THERMAL_EFFICIENCY,
) -> float:
    """Convenience wrapper chaining gas_floor_price -> system_margin_price —
    the full merit-order price for one settlement period."""
    floor = gas_floor_price(gas_price_gbp_per_mwh, thermal_efficiency)
    return system_margin_price(floor, demand_mw, renewable_generation_mw, gamma)
