"""Profile Class 1 (domestic unrestricted) half-hourly consumption shape.

Historical Ground Truth law: the shape values in sim/data/profile_class_1_gad.csv
are real published Group Average Demand (GAD, kW) figures for PC1 customers —
sourced from the UKERC Energy Data Centre archive ("Electricity user load
profiles by profile class", supplied by the Electricity Association via
Elexon Ltd, Open Access, 1997 reference year — the BSC's own modern API does
not expose historical profile-coefficient time series; see
docs/data-sources/profile-class-1.md for the full provenance trail). This is
the standard 5-season x 3-day-type structure documented in Elexon's BSC
Guidance Note "Load Profiles and their use in Electricity Settlement".

Energy per settlement period (kWh) = GAD (kW) x 0.5h, since each settlement
period is a half hour — no invented scaling factors.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 0b cross-model
delegation increment. The season-boundary date arithmetic required several
correction rounds; see docs/observability/token-log.md for what the model
got wrong and how it was caught (cross-checked against known UK clock-change
/ bank-holiday dates), which is itself the Phase 0b signal this increment
was built to produce.
"""

import csv
from datetime import date, datetime, timedelta

CSV_PATH = "sim/data/profile_class_1_gad.csv"

_SEASON_COLUMN_PREFIX = {
    "winter": "Wtr",
    "spring": "Spr",
    "summer": "Smr",
    "high_summer": "Hsr",
    "autumn": "Aut",
}
_DAYTYPE_COLUMN_SUFFIX = {"weekday": "Wd", "saturday": "Sat", "sunday": "Sun"}


def last_sunday_of_month(year: int, month: int) -> date:
    first_of_next = date(year + 1, 1, 1) if month == 12 else date(year, month + 1, 1)
    last_day = first_of_next - timedelta(days=1)
    return last_day - timedelta(days=(last_day.weekday() - 6) % 7)


def last_monday_of_month(year: int, month: int) -> date:
    first_of_next = date(year + 1, 1, 1) if month == 12 else date(year, month + 1, 1)
    last_day = first_of_next - timedelta(days=1)
    return last_day - timedelta(days=last_day.weekday())


def season_for_date(target_date: date) -> str:
    """Classify a date into one of the five BSC load-profile seasons.

    Boundaries (from Elexon's "Load Profiles" guidance note): winter runs
    from the BST->GMT clock change in October to the day before the
    following GMT->BST change in March; spring from that March change to
    the day before summer starts; summer is the 10-week period starting on
    the 16th Saturday before August Bank Holiday; high summer is the 6
    week 2 day period starting on the 6th Saturday before August Bank
    Holiday and ending the Sunday following it; autumn runs from the
    Monday following August Bank Holiday to the day before the October
    clock change. August Bank Holiday is always a Monday (last Monday of
    August), which fixes "the Nth Saturday before it" at bank_holiday minus
    (2 + 7*(N-1)) days, and "the Sunday following it" at bank_holiday plus
    6 days.
    """
    year = target_date.year
    clock_change_gmt_to_bst = last_sunday_of_month(year, 3)
    clock_change_bst_to_gmt = last_sunday_of_month(year, 10)
    august_bank_holiday = last_monday_of_month(year, 8)
    summer_start_saturday = august_bank_holiday - timedelta(days=2 + 7 * (16 - 1))
    high_summer_start_saturday = august_bank_holiday - timedelta(days=2 + 7 * (6 - 1))
    high_summer_end_sunday = august_bank_holiday + timedelta(days=6)

    if target_date < clock_change_gmt_to_bst or target_date >= clock_change_bst_to_gmt:
        return "winter"
    if target_date < summer_start_saturday:
        return "spring"
    if target_date < high_summer_start_saturday:
        return "summer"
    if target_date <= high_summer_end_sunday:
        return "high_summer"
    return "autumn"


def day_type_for_date(target_date: date) -> str:
    weekday = target_date.weekday()
    if weekday == 5:
        return "saturday"
    if weekday == 6:
        return "sunday"
    return "weekday"


def load_pc1_shape(target_date, csv_path: str = CSV_PATH) -> list[float]:
    """Return 48 half-hourly consumption values (kWh) for an average PC1
    customer on target_date, in chronological settlement-period order
    (index 0 = settlement period 1, 00:00-00:30).

    target_date is a 'YYYY-MM-DD' string or a date/datetime. The matching
    (season, day-type) column of sim/data/profile_class_1_gad.csv is read
    in row order and each GAD (kW) value is converted to kWh by x 0.5.
    """
    if isinstance(target_date, str):
        target_date = datetime.strptime(target_date, "%Y-%m-%d").date()

    column_name = (
        f"{_SEASON_COLUMN_PREFIX[season_for_date(target_date)]} "
        f"{_DAYTYPE_COLUMN_SUFFIX[day_type_for_date(target_date)]}"
    )

    with open(csv_path, newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        return [float(row[column_name]) * 0.5 for row in reader]


if __name__ == "__main__":
    shape = load_pc1_shape("2016-01-04")
    print(f"2016-01-04: {len(shape)} periods, daily total = {sum(shape):.2f} kWh")
