"""Enterprise risk physics — Value-at-Risk, collateral, and cost of capital.

Phase 1e asks a different question than Phase 1d: not "which hedge position
wins" but "is holding naked wholesale-price risk actually free?" In the real
world it is not — a supplier carrying unhedged exposure must post collateral
against the Value-at-Risk (VaR) of that exposure, and that collateral has a
cost (the cost of capital, WACC-driven). This module prices that cost from
real historical SSP volatility, exactly the way a real risk desk would.

Two volatility views are blended into one collateral figure (dual-window VaR):

  - sigma_recent: a rolling, point-in-time-safe measure of how volatile
    prices have actually been over the trailing 12 months — the "current
    market conditions" view. Expressed as a coefficient of variation
    (population standard deviation / mean of System Sell Price), a
    dimensionless relative-volatility figure.
  - sigma_stressed: a regulatory floor — the minimum volatility a supplier
    must hold capital against regardless of how calm the recent market looks,
    because regulators learned (the hard way, in 2021-2022) that calm periods
    can end abruptly. This floor is regime-dependent and changes on a real
    historical date (2023-01-01, when Ofgem's post-crisis capital adequacy
    reforms took effect) — the agent experiences this change exactly when it
    happened, which is a fact of the world at that date, not foresight.

Active collateral is whichever view demands more capital (max of the two) —
a real risk desk is never allowed to under-collateralise just because the
recent past looks calm. The cost of holding that collateral (Monthly Cost of
Capital = Active Collateral x WACC / 12) is what Phase 1e deducts from the
portfolio treasury every period, and it is the mechanism by which holding
naked risk stops being free: more naked exposure -> larger VaR -> larger
collateral -> larger capital cost -> lower net margin. The agent's existing
Phase 1d evolution rule (unchanged) now sees that drag baked into the margins
it compares, and can discover -- organically, from its own realised history,
exactly as it always has -- whether carrying less naked exposure pays for
itself.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator -- Phase 1e risk-engine
increment.
"""

import statistics
from datetime import date, timedelta

Z_SCORE_90_CONFIDENCE = 1.645      # one-tailed 90% confidence z-score for VaR
SIGMA_RECENT_LOOKBACK_DAYS = 365   # trailing window for the "current conditions" volatility view
SIGMA_STRESSED_PRE_REFORM = 0.50   # regulatory floor before Ofgem's post-crisis reform (lax, historically accurate)
SIGMA_STRESSED_POST_REFORM = 1.50  # regulatory floor from 2023-01-01 onwards (tightened after the 2021-2022 crisis)
REGULATORY_REGIME_CHANGE_DATE = "2023-01-01"  # the real date the stressed-VaR floor steps up
WACC = 0.10                        # weighted average cost of capital, annualised (mid-range for energy retail)


def calculate_sigma_recent(reference_date: str, system_price_records: list[dict], lookback_days: int = SIGMA_RECENT_LOOKBACK_DAYS) -> float:
    """The "current market conditions" volatility view, point-in-time safe.

    Filters system_price_records (each a dict with at least 'settlementDate'
    — an ISO date string — and 'systemSellPrice' — a float in GBP/MWh) to
    those whose settlementDate falls in the window
    [reference_date - lookback_days days, reference_date - 1 day] inclusive
    — STRICTLY BEFORE reference_date, so a contract term starting on a given
    date can never see that date's own price (the Point-in-Time Blindfold:
    the agent only ever knows what already happened).

    Computes the population standard deviation (statistics.pstdev) and the
    arithmetic mean (statistics.mean) of systemSellPrice across the filtered
    window, and returns their ratio (stdev / mean) — the coefficient of
    variation. Expressing volatility this way (as a fraction of the price
    level, rather than an absolute GBP/MWh figure) is what makes it directly
    comparable to the dimensionless regulatory floors in
    SIGMA_STRESSED_PRE_REFORM / SIGMA_STRESSED_POST_REFORM, and to
    get_sigma_stressed()'s return value.

    Raises ValueError with a clear message (including the window bounds and
    reference_date) if no records fall in the window.
    """
    ref_date = date.fromisoformat(reference_date)
    start_date = ref_date - timedelta(days=lookback_days)
    end_date = ref_date - timedelta(days=1)

    filtered_records = [
        record for record in system_price_records
        if start_date <= date.fromisoformat(record['settlementDate']) <= end_date
    ]

    if not filtered_records:
        raise ValueError(
            f"No system price records found in the window "
            f"[{start_date.isoformat()}, {end_date.isoformat()}] "
            f"required to assess sigma_recent for reference date {reference_date}"
        )

    prices = [record['systemSellPrice'] for record in filtered_records]
    stdev = statistics.pstdev(prices)
    mean = statistics.mean(prices)

    return stdev / mean


def get_sigma_stressed(reference_date: str) -> float:
    """The regulatory stressed-volatility floor in force on reference_date.

    Returns SIGMA_STRESSED_PRE_REFORM for any reference_date strictly before
    REGULATORY_REGIME_CHANGE_DATE, and SIGMA_STRESSED_POST_REFORM for any
    reference_date on or after it. Compare ISO date strings by converting
    both to date.fromisoformat() — do not compare the strings directly.

    This is a real historical regulatory change the agent experiences at the
    moment it takes effect — not a hint about the future. On 2022-12-31 the
    floor is still 0.50; on 2023-01-01 it is 1.50, because that is the date
    Ofgem's post-crisis capital adequacy reform took effect in this
    simulation's history, and the agent only ever knows the rules in force
    today, never the rules of tomorrow.
    """
    ref_date = date.fromisoformat(reference_date)
    change_date = date.fromisoformat(REGULATORY_REGIME_CHANGE_DATE)

    return SIGMA_STRESSED_POST_REFORM if ref_date >= change_date else SIGMA_STRESSED_PRE_REFORM


def calculate_var(sigma: float, naked_volume_kwh: float, forward_price_gbp_per_mwh: float) -> float:
    """Value-at-Risk in GBP for one volatility view of one naked exposure.

    VaR = Z_SCORE_90_CONFIDENCE * sigma * (naked_volume_kwh / 1000) * forward_price_gbp_per_mwh

    Dividing naked_volume_kwh by 1000 converts it to MWh so the result is
    unit-consistent: a dimensionless sigma, times a volume in MWh, times a
    price in GBP/MWh, gives a monetary figure in GBP — the capital a risk
    desk would need to hold against this exposure being sigma standard
    deviations worse than expected, at 90% one-tailed confidence.
    """
    return Z_SCORE_90_CONFIDENCE * sigma * (naked_volume_kwh / 1000) * forward_price_gbp_per_mwh


def calculate_active_collateral(var_current: float, var_stressed: float) -> float:
    """The capital a risk desk must actually hold: whichever view of the
    world demands more of it. A real desk is never allowed to under-
    collateralise just because recent conditions look calmer than the
    regulatory floor assumes — so this is simply max(var_current, var_stressed).
    """
    return max(var_current, var_stressed)


def calculate_monthly_cost_of_capital(active_collateral_gbp: float, wacc: float = WACC) -> float:
    """What it costs, per month, to hold that collateral — the capital isn't
    free even when nothing goes wrong; it's tied up and has an opportunity
    cost (WACC, annualised, divided by 12 for a monthly figure).

    Monthly Cost of Capital = active_collateral_gbp * wacc / 12
    """
    return active_collateral_gbp * wacc / 12


def compute_net_margin(gross_margin_gbp: float, capital_cost_gbp: float) -> float:
    """Net margin after the cost of capital is deducted.

    net_margin_gbp = gross_margin_gbp - capital_cost_gbp

    Consolidates the per-period net-margin calculation that previously lived
    inline in simulation/hedged_settlement.py — the cost of capital computed
    by calculate_monthly_cost_of_capital() is what this function deducts.
    """
    return gross_margin_gbp - capital_cost_gbp


def is_administration_triggered(treasury_balance_gbp: float) -> bool:
    """Whether the portfolio treasury balance forces an administration event.

    Administration triggers the moment the treasury cash balance reaches or
    falls below zero (treasury_balance_gbp <= 0). Consolidates the check
    duplicated across the simulation/run_phase*.py scripts.
    """
    return treasury_balance_gbp <= 0


def assess_term_risk(term_start_date: str, naked_volume_kwh: float, forward_price_gbp_per_mwh: float, system_price_records: list[dict], wacc: float = WACC) -> dict:
    """The single entry point the orchestration calls once per contract term
    (and, separately, once for any naked counterfactual scenario it wants to
    price under the same physics): runs the full dual-window VaR -> active
    collateral -> monthly cost of capital pipeline and returns every
    intermediate figure so the run can report and audit each step.

    Calls, in order:
      sigma_recent = calculate_sigma_recent(term_start_date, system_price_records)
      sigma_stressed = get_sigma_stressed(term_start_date)
      var_current = calculate_var(sigma_recent, naked_volume_kwh, forward_price_gbp_per_mwh)
      var_stressed = calculate_var(sigma_stressed, naked_volume_kwh, forward_price_gbp_per_mwh)
      active_collateral_gbp = calculate_active_collateral(var_current, var_stressed)
      monthly_cost_of_capital_gbp = calculate_monthly_cost_of_capital(active_collateral_gbp, wacc)

    Returns a dict with exactly these keys: sigma_recent, sigma_stressed,
    var_current_gbp, var_stressed_gbp, active_collateral_gbp,
    monthly_cost_of_capital_gbp — every number that went into the final
    figure, in the order they were computed, so each step is independently
    auditable from a printed log alone.
    """
    sigma_recent = calculate_sigma_recent(term_start_date, system_price_records)
    sigma_stressed = get_sigma_stressed(term_start_date)
    var_current = calculate_var(sigma_recent, naked_volume_kwh, forward_price_gbp_per_mwh)
    var_stressed = calculate_var(sigma_stressed, naked_volume_kwh, forward_price_gbp_per_mwh)
    active_collateral_gbp = calculate_active_collateral(var_current, var_stressed)
    monthly_cost_of_capital_gbp = calculate_monthly_cost_of_capital(active_collateral_gbp, wacc)

    return {
        "sigma_recent": sigma_recent,
        "sigma_stressed": sigma_stressed,
        "var_current_gbp": var_current,
        "var_stressed_gbp": var_stressed,
        "active_collateral_gbp": active_collateral_gbp,
        "monthly_cost_of_capital_gbp": monthly_cost_of_capital_gbp,
    }
