"""Retrieval of historical System Sell Price (SSP) / System Buy Price (SBP)
records over a date range, from Elexon.

Historical Ground Truth law: this hits the real Elexon Insights Solution API
(data.elexon.co.uk) — no synthetic data. See docs/data-sources/elexon.md for
the endpoint shape this depends on, and docs/simulation-period.md for why
day-level record counts vary (occasional missing periods, 46/50-period DST
transition days) — this is normal and not treated as an error here.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 0b cross-model
delegation increment.
"""

from datetime import datetime, timedelta

import requests

BASE_URL = "https://data.elexon.co.uk/bmrs/api/v1"
SYSTEM_PRICES_ENDPOINT = "/balancing/settlement/system-prices/{settlement_date}"


def get_system_prices_range(start_date: str, end_date: str) -> list[dict]:
    """Return raw SSP/SBP settlement-period records for every day in
    [start_date, end_date] inclusive, as a flat list, in chronological order.

    start_date and end_date are 'YYYY-MM-DD' strings. Days that return a
    non-200 response or no data are treated as zero records, not an error —
    the per-date endpoint is queried one day at a time and concatenated;
    record counts per day are passed through unmodified (see module docstring).
    """
    start = datetime.strptime(start_date, "%Y-%m-%d")
    end = datetime.strptime(end_date, "%Y-%m-%d")

    records = []
    current = start
    while current <= end:
        date_str = current.strftime("%Y-%m-%d")
        url = BASE_URL + SYSTEM_PRICES_ENDPOINT.format(settlement_date=date_str)
        response = requests.get(url)
        if response.status_code == 200:
            records.extend(response.json().get("data", []))
        current += timedelta(days=1)

    return records


if __name__ == "__main__":
    import json

    sample = get_system_prices_range("2016-01-01", "2016-01-03")
    print(f"{len(sample)} records retrieved")
    print(json.dumps(sample[0], indent=2))
