"""Retrieval of historical System Sell Price (SSP) / System Buy Price (SBP)
records over a date range, from Elexon.

Historical Ground Truth law: this hits the real Elexon Insights Solution API
(data.elexon.co.uk) — no synthetic data. See docs/data-sources/elexon.md for
the endpoint shape this depends on, and docs/simulation-period.md for why
day-level record counts vary (occasional missing periods, 46/50-period DST
transition days) — this is normal and not treated as an error here.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 0b cross-model
delegation increment.
"""

import time
from datetime import datetime, timedelta

import requests

BASE_URL = "https://data.elexon.co.uk/bmrs/api/v1"
SYSTEM_PRICES_ENDPOINT = "/balancing/settlement/system-prices/{settlement_date}"

#: The first whole day the published record holds. Re-probed 2026-10-06: 2015-10-03 (the start of a
#: 2016-01-01 contract's 90-day lookback), 2015-11-04 and 2015-11-05 return no records, 2015-11-06
#: one, 2015-11-07 a full 48. So, unlike gas (`sim.gas_prices_history.RECORD_START`), this record
#: cannot be extended to price a day-one founder off a full lookback, and the short window is
#: declared rather than filled.
RECORD_START = "2015-11-07"
SHORT_RECORD_REASON = (
    "Elexon's system-price record begins 2015-11-07: BSC Modification P305 replaced dual "
    "SSP/SBP imbalance pricing with a single price in November 2015, and the published dataset "
    "holds nothing under the current methodology before it (docs/simulation-period.md). A first "
    "term starting before 2016-02-05 prices off only the days since then."
)

_session = requests.Session()

#: Retries for a non-200 day before the range is refused. Not a domain constant: it bounds how long
#: a throttled fetch waits (1+2+4 s), and any value refuses rather than drops a persistent failure.
FETCH_RETRIES = 3


class SystemPricesFetchError(RuntimeError):
    """A day's system prices could not be fetched, so the range would have a hole in it."""


def get_system_prices_range(start_date: str, end_date: str) -> list[dict]:
    """Return raw SSP/SBP settlement-period records for every day in
    [start_date, end_date] inclusive, as a flat list, in chronological order.

    start_date and end_date are 'YYYY-MM-DD' strings. A day with no data
    comes back as a 200 with an empty list and contributes zero records (probed
    2026-10-07: 2015-11-04 is 200/0). A non-200 is a FAILED FETCH, not an empty
    day: it is retried, and if it persists the range is refused naming the day.
    It used to be read as zero records, and on 2026-10-07 a throttled fetch
    returned 144,361 of 168,026 records with Q3 2020 empty -- a different world,
    silently, which only failed because a forward price had no lookback left.
    Record counts per day are passed through unmodified (see module docstring).

    Requests reuse a module-level Session for connection pooling — without it,
    each call pays a fresh TLS handshake (~12s vs ~0.05s reused).
    """
    start = datetime.strptime(start_date, "%Y-%m-%d")
    end = datetime.strptime(end_date, "%Y-%m-%d")

    records = []
    current = start
    while current <= end:
        date_str = current.strftime("%Y-%m-%d")
        url = BASE_URL + SYSTEM_PRICES_ENDPOINT.format(settlement_date=date_str)
        response = _session.get(url)
        for attempt in range(FETCH_RETRIES):
            if response.status_code == 200:
                break
            time.sleep(2 ** attempt)
            response = _session.get(url)
        if response.status_code != 200:
            raise SystemPricesFetchError(
                f"Elexon system prices for {date_str} returned HTTP {response.status_code} after "
                f"{FETCH_RETRIES} retries; refusing the range [{start_date}, {end_date}] rather than "
                "returning it with the day missing."
            )
        records.extend(response.json().get("data", []))
        current += timedelta(days=1)

    return records


if __name__ == "__main__":
    import json

    sample = get_system_prices_range("2016-01-01", "2016-01-03")
    print(f"{len(sample)} records retrieved")
    print(json.dumps(sample[0], indent=2))
