"""Single-contract-term, hedge-aware settlement run.

Mirrors simulation/settlement.py's run_settlement loop structure exactly —
same per-customer, per-date, per-settlement-period iteration over the
reporting window, the same price_lookup-by-(date, period) approach — but
for exactly ONE contract term at a time, and computing revenue/cost/margin
through sim.hedging.settle_hedged_period (hedge-aware) instead of the pure
spot-only calculation run_settlement performs.

Why one term at a time rather than a whole customer's history in one call:
Phase 1d's agent decides its hedge_fraction per term and evolves it only
after that term's outcomes are fully known (simulation/run_phase1d.py owns
that sequencing). Settling term-by-term is what makes "no foresight"
structural here rather than a documentation promise — the function simply
has no way to see beyond the one term it's asked to settle.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 1d hedging
increment.
"""

from datetime import date, timedelta

from sim.hedging import settle_hedged_period


def run_hedged_term(
    customer_id: str,
    term_start_date: str,
    term_end_date: str,
    fixed_tariff_rate_gbp_per_mwh: float,
    hedge_price_gbp_per_mwh: float,
    hedge_fraction: float,
    consumption_shape,
    system_price_records: list[dict],
) -> list[dict]:
    """Settle one customer's one contract term, hedge-aware, for every
    calendar date in [term_start_date, term_end_date) and every settlement
    period (1-48) with a matching real price record.

    term_start_date/term_end_date bound exactly the active-contract window
    for THIS term (the caller — simulation/run_phase1d.py — is responsible
    for deriving term_end_date from the renewal schedule and clipping both
    ends to the overall reporting window; this function does no clipping
    or contract-length arithmetic of its own, unlike run_settlement, since
    it settles one already-bounded term rather than a customer's whole
    multi-term tenure).

    fixed_tariff_rate_gbp_per_mwh is the customer's contracted unit rate for
    this term (what they pay). hedge_price_gbp_per_mwh is the forward price
    locked in at this term's start date (what the supplier pays for the
    hedged share). hedge_fraction (0.0-1.0) is the agent's chosen split for
    this term, fixed for its whole duration — sim.hedging.settle_hedged_period
    does the actual per-period economics.

    consumption_shape(date_str) returns 48 kWh floats indexed 0..47 for
    settlement periods 1..48. system_price_records supplies the real System
    Sell Price (£/MWh), looked up by exact (settlementDate, settlementPeriod)
    match — periods with no matching price record are skipped, not guessed,
    exactly as run_settlement does.

    Returns a flat list of records in chronological (date, then period)
    order, each:
      {customer_id, settlement_date, settlement_period, consumption_kwh,
       unit_rate_gbp_per_mwh, hedge_price_gbp_per_mwh, hedge_fraction,
       hedged_volume_kwh, unhedged_volume_kwh, revenue_gbp,
       wholesale_cost_gbp, margin_gbp}
    """
    start = date.fromisoformat(term_start_date)
    end = date.fromisoformat(term_end_date)

    price_lookup = {
        (record["settlementDate"], record["settlementPeriod"]): record["systemSellPrice"]
        for record in system_price_records
    }

    records = []
    current_date = start
    while current_date < end:
        date_str = current_date.isoformat()
        shape = consumption_shape(date_str)

        for period in range(1, 49):
            spot_price = price_lookup.get((date_str, period))
            if spot_price is None:
                continue

            consumption_kwh = shape[period - 1]
            settled = settle_hedged_period(
                consumption_kwh,
                fixed_tariff_rate_gbp_per_mwh,
                hedge_price_gbp_per_mwh,
                hedge_fraction,
                spot_price,
            )

            records.append({
                "customer_id": customer_id,
                "settlement_date": date_str,
                "settlement_period": period,
                "consumption_kwh": consumption_kwh,
                "unit_rate_gbp_per_mwh": fixed_tariff_rate_gbp_per_mwh,
                "hedge_price_gbp_per_mwh": hedge_price_gbp_per_mwh,
                "hedge_fraction": hedge_fraction,
                "hedged_volume_kwh": settled["hedged_volume_kwh"],
                "unhedged_volume_kwh": settled["unhedged_volume_kwh"],
                "revenue_gbp": settled["revenue_gbp"],
                "wholesale_cost_gbp": settled["wholesale_cost_gbp"],
                "margin_gbp": settled["margin_gbp"],
            })

        current_date += timedelta(days=1)

    return records
