"""Single-contract-term, hedge-aware settlement run.

Mirrors simulation/settlement.py's run_settlement loop structure exactly —
same per-customer, per-date, per-settlement-period iteration over the
reporting window, the same price_lookup-by-(date, period) approach — but
for exactly ONE contract term at a time, and computing revenue/cost/margin
through sim.hedging.settle_hedged_period (hedge-aware) instead of the pure
spot-only calculation run_settlement performs.

Why one term at a time rather than a whole customer's history in one call:
Phase 1d's agent decides its hedge_fraction per term and evolves it only
after that term's outcomes are fully known (simulation/run_phase1d.py owns
that sequencing). Settling term-by-term is what makes "no foresight"
structural here rather than a documentation promise — the function simply
has no way to see beyond the one term it's asked to settle.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 1d hedging
increment.

Phase 1e increment (hand-written — orchestration-adjacent code touching
this module's existing settlement-record schema is exactly the class of
edit Phase 1d found local delegation gets wrong): folds the cost of
capital into every period's P&L. sim.risk_engine prices, once per term,
how much it costs per month to hold collateral against this term's naked
exposure (Active_Collateral x WACC / 12) — a single figure, fixed for the
term's duration because the collateral assessment itself is fixed at term
start. That monthly figure is allocated proportionally across every real
settled period in each calendar month the term touches (dividing evenly by
how many periods actually settled that month — not an assumed 48/day,
which would overcount on the occasional 46-period DST day and undercount
on a 50-period one). The result, capital_cost_gbp, is recorded per period
alongside a new net_margin_gbp = margin_gbp - capital_cost_gbp — the
figure that actually moves the shared portfolio treasury in
simulation/run_phase1e.py, and the one that finally makes holding naked
risk show up as something other than free.
"""

from collections import defaultdict
from datetime import date, timedelta

from sim.hedging import settle_hedged_period
from sim.risk_engine import compute_net_margin
from simulation.policy_costs import (
    get_ccl_per_mwh,
    get_cfd_levy_per_mwh,
    get_cm_levy_per_mwh,
    get_fit_levy_per_mwh,
    get_mutualization_levy_per_mwh,
    get_electricity_network_cost_per_mwh,
    get_ro_cost_per_mwh,
)
from simulation.tou_periods import is_peak_period


def run_hedged_term(
    customer_id: str,
    term_start_date: str,
    term_end_date: str,
    fixed_tariff_rate_gbp_per_mwh: float,
    hedge_price_gbp_per_mwh: float,
    hedge_fraction: float,
    monthly_cost_of_capital_gbp: float,
    consumption_shape,
    system_price_records: list[dict],
    tou_rates: tuple[float, float] | None = None,
    segment: str = "resi",
    pass_through: bool = False,
) -> list[dict]:
    """Settle one customer's one contract term, hedge-aware, for every
    calendar date in [term_start_date, term_end_date) and every settlement
    period (1-48) with a matching real price record.

    term_start_date/term_end_date bound exactly the active-contract window
    for THIS term (the caller — simulation/run_phase1d.py — is responsible
    for deriving term_end_date from the renewal schedule and clipping both
    ends to the overall reporting window; this function does no clipping
    or contract-length arithmetic of its own, unlike run_settlement, since
    it settles one already-bounded term rather than a customer's whole
    multi-term tenure).

    fixed_tariff_rate_gbp_per_mwh is the customer's contracted unit rate for
    this term (what they pay). hedge_price_gbp_per_mwh is the forward price
    locked in at this term's start date (what the supplier pays for the
    hedged share). hedge_fraction (0.0-1.0) is the agent's chosen split for
    this term, fixed for its whole duration — sim.hedging.settle_hedged_period
    does the actual per-period economics.

    monthly_cost_of_capital_gbp is the term-level collateral cost per month,
    computed by sim.risk_engine.assess_term_risk for this term's specific
    naked exposure. It is fixed for the entire term (collateral is sized once
    at term start), and allocated evenly across the periods that actually
    settled in each calendar month (not an assumed constant 48/day).

    consumption_shape(date_str) returns 48 kWh floats indexed 0..47 for
    settlement periods 1..48. system_price_records supplies the real System
    Sell Price (£/MWh), looked up by exact (settlementDate, settlementPeriod)
    match — periods with no matching price record are skipped, not guessed,
    exactly as run_settlement does.

    Returns a flat list of records in chronological (date, then period)
    order, each:
      {customer_id, settlement_date, settlement_period, consumption_kwh,
       unit_rate_gbp_per_mwh, hedge_price_gbp_per_mwh, hedge_fraction,
       hedged_volume_kwh, unhedged_volume_kwh, revenue_gbp,
       wholesale_cost_gbp, margin_gbp, ro_levy_gbp, cfd_levy_gbp,
       policy_cost_gbp, capital_cost_gbp, net_margin_gbp}
    where:
      capital_cost_gbp = monthly_cost_of_capital_gbp / (periods in that
        calendar month for this term)
      ro_levy_gbp / cfd_levy_gbp = RO + CfD levies for the settlement date
        year (Phase 21a); cfd_levy_gbp is negative in 2022 (crisis rebate)
      ccl_gbp = CCL for this period (Phase 27b); 0.0 for resi (exempt),
        main CCL rate for SME/I&C business customers (remitted to HMRC)
      policy_cost_gbp = ro_levy_gbp + cfd_levy_gbp + ccl_gbp + cm_levy_gbp + fit_levy_gbp
      cm_levy_gbp = Capacity Market levy (Phase 30a) — applies to all segments
        including domestic (no exemption); highly variable £0.5–7.3/MWh by year
      fit_levy_gbp = Feed-in Tariff levelisation levy (Phase 31a) — applies to all
        segments (no domestic exemption); rising trend £4.1–8.5/MWh 2016–2024
      network_cost_gbp = DUoS + TNUoS for resi/SME; DUoS only for I&C
        (Phase 29a — I&C Triad TNUoS tracked separately in triad.py)
      net_margin_gbp = margin_gbp - policy_cost_gbp - network_cost_gbp - capital_cost_gbp
    """
    start = date.fromisoformat(term_start_date)
    end = date.fromisoformat(term_end_date)

    price_lookup = {
        (record["settlementDate"], record["settlementPeriod"]): record["systemSellPrice"]
        for record in system_price_records
    }

    records = []
    current_date = start
    while current_date < end:
        date_str = current_date.isoformat()
        shape = consumption_shape(date_str)

        for period in range(1, 49):
            spot_price = price_lookup.get((date_str, period))
            if spot_price is None:
                continue

            consumption_kwh = shape[period - 1]
            if tou_rates is not None:
                peak_rate, offpeak_rate = tou_rates
                period_rate = peak_rate if is_peak_period(date_str, period) else offpeak_rate
            else:
                period_rate = fixed_tariff_rate_gbp_per_mwh
            settled = settle_hedged_period(
                consumption_kwh,
                period_rate,
                hedge_price_gbp_per_mwh,
                hedge_fraction,
                spot_price,
            )

            # Phase 21a: RO + CfD levy for this settlement date's year.
            # Uses actual settlement year, not term-start year, so cross-year
            # terms (e.g. July 2021–June 2022) naturally reflect the 2022
            # negative CfD rebate on H1 2022 settlement periods.
            # Phase 27b: CCL (Climate Change Levy) — 0 for resi (domestic exempt),
            # main CCL rate for business (SME/I&C) customers, remitted to HMRC.
            consumption_mwh = consumption_kwh / 1000.0
            ro_levy = get_ro_cost_per_mwh(date_str) * consumption_mwh
            cfd_levy = get_cfd_levy_per_mwh(date_str) * consumption_mwh
            ccl = get_ccl_per_mwh(date_str, segment) * consumption_mwh
            # Phase 30a: CM levy applies to all segments — no domestic exemption.
            cm_levy = get_cm_levy_per_mwh(date_str) * consumption_mwh
            # Phase 31a: FiT levy applies to all segments — no domestic exemption.
            fit_levy = get_fit_levy_per_mwh(date_str) * consumption_mwh
            # Phase 54: SoLR mutualization levy (2021-2022 supplier failure recovery)
            mutualization_levy = get_mutualization_levy_per_mwh(date_str) * consumption_mwh
            # Phase 29a: network charges. Resi/SME: DUoS + TNUoS unit rate.
            # I&C: DUoS only (Triad TNUoS is an annual lump, tracked in triad.py).
            network_cost = get_electricity_network_cost_per_mwh(date_str, segment) * consumption_mwh

            # Phase 40a: for pass-through tariffs, revenue includes actual policy + network
            # costs (passed through to customer). These cancel out in net_margin so the
            # company's margin is purely from the wholesale spread. For fixed tariffs,
            # policy/network are baked into the locked unit_rate; any divergence from
            # actual costs accrues to the company (policy cost risk).
            policy_total = ro_levy + cfd_levy + ccl + cm_levy + fit_levy + mutualization_levy
            if pass_through:
                revenue_gbp = settled["revenue_gbp"] + policy_total + network_cost
                margin_gbp = revenue_gbp - settled["wholesale_cost_gbp"]
            else:
                revenue_gbp = settled["revenue_gbp"]
                margin_gbp = settled["margin_gbp"]

            records.append({
                "customer_id": customer_id,
                "settlement_date": date_str,
                "settlement_period": period,
                "consumption_kwh": consumption_kwh,
                "unit_rate_gbp_per_mwh": period_rate,
                "hedge_price_gbp_per_mwh": hedge_price_gbp_per_mwh,
                "hedge_fraction": hedge_fraction,
                "hedged_volume_kwh": settled["hedged_volume_kwh"],
                "unhedged_volume_kwh": settled["unhedged_volume_kwh"],
                "revenue_gbp": revenue_gbp,
                "wholesale_cost_gbp": settled["wholesale_cost_gbp"],
                "margin_gbp": margin_gbp,
                "ro_levy_gbp": ro_levy,
                "cfd_levy_gbp": cfd_levy,
                "ccl_gbp": ccl,
                "cm_levy_gbp": cm_levy,
                "fit_levy_gbp": fit_levy,
                "mutualization_levy_gbp": mutualization_levy,
                "policy_cost_gbp": policy_total,
                "network_cost_gbp": network_cost,
            })

        current_date += timedelta(days=1)

    # Capital cost is a term-level figure (collateral is sized once, at term
    # start) but the treasury is debited every period — so allocate it
    # proportionally across whichever periods actually settled in each
    # calendar month this term touches. Grouping by the records that exist
    # (rather than assuming 48/day) absorbs DST's 46/50-period days and any
    # missing-price gaps exactly, with no special-casing.
    records_by_month = defaultdict(list)
    for record in records:
        records_by_month[record["settlement_date"][:7]].append(record)

    for month_records in records_by_month.values():
        capital_cost_per_period_gbp = monthly_cost_of_capital_gbp / len(month_records)
        for record in month_records:
            record["capital_cost_gbp"] = capital_cost_per_period_gbp
            # net_margin deducts both policy costs (RO/CfD levies paid to Ofgem/LCCC)
            # and the cost of capital. Phase 21a: policy_cost_gbp can be negative in 2022
            # (CfD rebate exceeds RO), which boosts net_margin by that amount.
            record["net_margin_gbp"] = compute_net_margin(
                record["margin_gbp"] - record["policy_cost_gbp"] - record["network_cost_gbp"],
                capital_cost_per_period_gbp,
            )

    return records


def run_deemed_term(
    customer_id: str,
    term_start_date: str,
    term_end_date: str,
    deemed_premium: float,
    consumption_shape,
    system_price_records: list[dict],
    segment: str = "resi",
) -> list[dict]:
    """Phase 40c: settle an out-of-contract deemed period.

    The customer has no fixed-term contract. They are billed at spot price
    × (1 + deemed_premium) each settlement period. The company buys at spot
    (no forward hedge commitment). Capital cost is zero for deemed periods
    (no collateral is sized — buying is fully spot-indexed).

    Revenue = spot × (1 + premium) × consumption
    Wholesale cost = spot × consumption
    Gross margin = spot × premium × consumption
    Net margin = gross margin − policy cost − network cost
    """
    start = date.fromisoformat(term_start_date)
    end = date.fromisoformat(term_end_date)

    price_lookup = {
        (record["settlementDate"], record["settlementPeriod"]): record["systemSellPrice"]
        for record in system_price_records
    }

    records = []
    current_date = start
    while current_date < end:
        date_str = current_date.isoformat()
        shape = consumption_shape(date_str)

        for period in range(1, 49):
            spot_price = price_lookup.get((date_str, period))
            if spot_price is None:
                continue

            consumption_kwh = shape[period - 1]
            consumption_mwh = consumption_kwh / 1000.0

            revenue_gbp = spot_price * (1.0 + deemed_premium) * consumption_mwh
            wholesale_cost_gbp = spot_price * consumption_mwh
            margin_gbp = revenue_gbp - wholesale_cost_gbp

            ro_levy = get_ro_cost_per_mwh(date_str) * consumption_mwh
            cfd_levy = get_cfd_levy_per_mwh(date_str) * consumption_mwh
            ccl = get_ccl_per_mwh(date_str, segment) * consumption_mwh
            cm_levy = get_cm_levy_per_mwh(date_str) * consumption_mwh
            fit_levy = get_fit_levy_per_mwh(date_str) * consumption_mwh
            # Phase 54: SoLR mutualization levy
            mutualization_levy = get_mutualization_levy_per_mwh(date_str) * consumption_mwh
            network_cost = get_electricity_network_cost_per_mwh(date_str, segment) * consumption_mwh
            policy_total = ro_levy + cfd_levy + ccl + cm_levy + fit_levy + mutualization_levy

            records.append({
                "customer_id": customer_id,
                "settlement_date": date_str,
                "settlement_period": period,
                "consumption_kwh": consumption_kwh,
                "unit_rate_gbp_per_mwh": spot_price * (1.0 + deemed_premium),
                "hedge_price_gbp_per_mwh": None,
                "hedge_fraction": 0.0,
                "hedged_volume_kwh": 0.0,
                "unhedged_volume_kwh": consumption_kwh,
                "revenue_gbp": revenue_gbp,
                "wholesale_cost_gbp": wholesale_cost_gbp,
                "margin_gbp": margin_gbp,
                "ro_levy_gbp": ro_levy,
                "cfd_levy_gbp": cfd_levy,
                "ccl_gbp": ccl,
                "cm_levy_gbp": cm_levy,
                "fit_levy_gbp": fit_levy,
                "mutualization_levy_gbp": mutualization_levy,
                "policy_cost_gbp": policy_total,
                "network_cost_gbp": network_cost,
                "capital_cost_gbp": 0.0,  # no forward hedge commitment in deemed periods
                "net_margin_gbp": compute_net_margin(
                    margin_gbp - policy_total - network_cost, 0.0
                ),
                "tariff_type": "deemed",
            })

        current_date += timedelta(days=1)

    return records


# ---------------------------------------------------------------------------
# Phase 41a — Flex/trading tariff settlement
# ---------------------------------------------------------------------------

FLEX_REFERENCE_WINDOW_DAYS: int = 7


def run_flex_term(
    customer_id: str,
    term_start_date: str,
    term_end_date: str,
    flex_markup_per_mwh: float,
    consumption_shape,
    system_price_records: list[dict],
    segment: str = "I&C",
    reference_window_days: int = FLEX_REFERENCE_WINDOW_DAYS,
) -> list[dict]:
    """Phase 41a: settle a flex/trading tariff term.

    The customer holds a flex contract: no locked unit rate. They call volumes
    weekly at the day-ahead reference price (7-day rolling average of daily
    spot). The supplier earns a fixed trading desk markup on each unit sold.

    Revenue = (ref_price + markup) × consumption
    Wholesale cost = ref_price × consumption   (supplier hedges at reference)
    Gross margin = markup × consumption         (pure trading margin)
    Net margin = gross margin − policy cost − network cost
    Capital cost = 0 (no naked exposure; position hedged weekly at reference)
    Hedge fraction = 1.0 (fully covered at reference price)

    The reference price for each period is computed as the arithmetic mean of
    daily mean spot over the prior `reference_window_days` days — a backward-
    looking proxy for the week-ahead index price at time of calling, preserving
    the Point-in-Time Blindfold: no future prices are ever used.
    """
    start = date.fromisoformat(term_start_date)
    end = date.fromisoformat(term_end_date)

    # Build daily mean spot lookup from system_price_records
    daily_means: dict[str, float] = {}
    daily_buckets: dict[str, list[float]] = {}
    for r in system_price_records:
        daily_buckets.setdefault(r["settlementDate"], []).append(r["systemSellPrice"])
    for d_str, prices in daily_buckets.items():
        import statistics as _stats
        daily_means[d_str] = _stats.mean(prices)

    # Ordered list of dates for rolling window computation
    sorted_dates = sorted(daily_means.keys())

    def _ref_price(period_date_str: str) -> float:
        """7-day rolling mean of daily spot prior to period_date (PIT safe)."""
        period_d = date.fromisoformat(period_date_str)
        window_end = period_d - timedelta(days=1)
        window_start = period_d - timedelta(days=reference_window_days)
        window_prices = [
            daily_means[d] for d in sorted_dates
            if window_start <= date.fromisoformat(d) <= window_end and d in daily_means
        ]
        if not window_prices:
            # Fallback: use most recent available daily mean
            available = [daily_means[d] for d in sorted_dates if d < period_date_str]
            return available[-1] if available else 50.0
        import statistics as _stats
        return _stats.mean(window_prices)

    price_lookup = {
        (r["settlementDate"], r["settlementPeriod"]): r["systemSellPrice"]
        for r in system_price_records
    }

    records = []
    current_date = start
    while current_date < end:
        date_str = current_date.isoformat()
        shape = consumption_shape(date_str)
        ref_price = _ref_price(date_str)

        for period in range(1, 49):
            spot_price = price_lookup.get((date_str, period))
            if spot_price is None:
                continue

            consumption_kwh = shape[period - 1]
            consumption_mwh = consumption_kwh / 1000.0

            revenue_gbp = (ref_price + flex_markup_per_mwh) * consumption_mwh
            wholesale_cost_gbp = ref_price * consumption_mwh
            margin_gbp = flex_markup_per_mwh * consumption_mwh

            ro_levy = get_ro_cost_per_mwh(date_str) * consumption_mwh
            cfd_levy = get_cfd_levy_per_mwh(date_str) * consumption_mwh
            ccl = get_ccl_per_mwh(date_str, segment) * consumption_mwh
            cm_levy = get_cm_levy_per_mwh(date_str) * consumption_mwh
            fit_levy = get_fit_levy_per_mwh(date_str) * consumption_mwh
            # Phase 54: SoLR mutualization levy
            mutualization_levy = get_mutualization_levy_per_mwh(date_str) * consumption_mwh
            network_cost = get_electricity_network_cost_per_mwh(date_str, segment) * consumption_mwh
            policy_total = ro_levy + cfd_levy + ccl + cm_levy + fit_levy + mutualization_levy

            records.append({
                "customer_id": customer_id,
                "settlement_date": date_str,
                "settlement_period": period,
                "consumption_kwh": consumption_kwh,
                "unit_rate_gbp_per_mwh": ref_price + flex_markup_per_mwh,
                "flex_reference_price_gbp_per_mwh": ref_price,
                "flex_markup_per_mwh": flex_markup_per_mwh,
                "hedge_price_gbp_per_mwh": ref_price,
                "hedge_fraction": 1.0,
                "hedged_volume_kwh": consumption_kwh,
                "unhedged_volume_kwh": 0.0,
                "revenue_gbp": revenue_gbp,
                "wholesale_cost_gbp": wholesale_cost_gbp,
                "margin_gbp": margin_gbp,
                "ro_levy_gbp": ro_levy,
                "cfd_levy_gbp": cfd_levy,
                "ccl_gbp": ccl,
                "cm_levy_gbp": cm_levy,
                "fit_levy_gbp": fit_levy,
                "mutualization_levy_gbp": mutualization_levy,
                "policy_cost_gbp": policy_total,
                "network_cost_gbp": network_cost,
                "capital_cost_gbp": 0.0,
                "net_margin_gbp": compute_net_margin(
                    margin_gbp - policy_total - network_cost, 0.0
                ),
                "tariff_type": "flex",
                "commodity": "electricity",
            })

        current_date += timedelta(days=1)

    return records
