"""Single-contract-term, hedge-aware settlement run.

Mirrors simulation/settlement.py's run_settlement loop structure exactly —
same per-customer, per-date, per-settlement-period iteration over the
reporting window, the same price_lookup-by-(date, period) approach — but
for exactly ONE contract term at a time, and computing revenue/cost/margin
through sim.hedging.settle_hedged_period (hedge-aware) instead of the pure
spot-only calculation run_settlement performs.

Why one term at a time rather than a whole customer's history in one call:
Phase 1d's agent decides its hedge_fraction per term and evolves it only
after that term's outcomes are fully known (simulation/run_phase1d.py owns
that sequencing). Settling term-by-term is what makes "no foresight"
structural here rather than a documentation promise — the function simply
has no way to see beyond the one term it's asked to settle.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 1d hedging
increment.

Phase 1e increment (hand-written — orchestration-adjacent code touching
this module's existing settlement-record schema is exactly the class of
edit Phase 1d found local delegation gets wrong): folds the cost of
capital into every period's P&L. sim.risk_engine prices, once per term,
how much it costs per month to hold collateral against this term's naked
exposure (Active_Collateral x WACC / 12) — a single figure, fixed for the
term's duration because the collateral assessment itself is fixed at term
start. That monthly figure is allocated proportionally across every real
settled period in each calendar month the term touches (dividing evenly by
how many periods actually settled that month — not an assumed 48/day,
which would overcount on the occasional 46-period DST day and undercount
on a 50-period one). The result, capital_cost_gbp, is recorded per period
alongside a new net_margin_gbp = margin_gbp - capital_cost_gbp — the
figure that actually moves the shared portfolio treasury in
simulation/run_phase1e.py, and the one that finally makes holding naked
risk show up as something other than free.
"""

from collections import defaultdict
from datetime import date, timedelta

from sim.hedging import settle_hedged_period
from sim.risk_engine import compute_net_margin
from simulation.tou_periods import is_peak_period


def run_hedged_term(
    customer_id: str,
    term_start_date: str,
    term_end_date: str,
    fixed_tariff_rate_gbp_per_mwh: float,
    hedge_price_gbp_per_mwh: float,
    hedge_fraction: float,
    monthly_cost_of_capital_gbp: float,
    consumption_shape,
    system_price_records: list[dict],
    tou_rates: tuple[float, float] | None = None,
) -> list[dict]:
    """Settle one customer's one contract term, hedge-aware, for every
    calendar date in [term_start_date, term_end_date) and every settlement
    period (1-48) with a matching real price record.

    term_start_date/term_end_date bound exactly the active-contract window
    for THIS term (the caller — simulation/run_phase1d.py — is responsible
    for deriving term_end_date from the renewal schedule and clipping both
    ends to the overall reporting window; this function does no clipping
    or contract-length arithmetic of its own, unlike run_settlement, since
    it settles one already-bounded term rather than a customer's whole
    multi-term tenure).

    fixed_tariff_rate_gbp_per_mwh is the customer's contracted unit rate for
    this term (what they pay). hedge_price_gbp_per_mwh is the forward price
    locked in at this term's start date (what the supplier pays for the
    hedged share). hedge_fraction (0.0-1.0) is the agent's chosen split for
    this term, fixed for its whole duration — sim.hedging.settle_hedged_period
    does the actual per-period economics.

    monthly_cost_of_capital_gbp is the term-level collateral cost per month,
    computed by sim.risk_engine.assess_term_risk for this term's specific
    naked exposure. It is fixed for the entire term (collateral is sized once
    at term start), and allocated evenly across the periods that actually
    settled in each calendar month (not an assumed constant 48/day).

    consumption_shape(date_str) returns 48 kWh floats indexed 0..47 for
    settlement periods 1..48. system_price_records supplies the real System
    Sell Price (£/MWh), looked up by exact (settlementDate, settlementPeriod)
    match — periods with no matching price record are skipped, not guessed,
    exactly as run_settlement does.

    Returns a flat list of records in chronological (date, then period)
    order, each:
      {customer_id, settlement_date, settlement_period, consumption_kwh,
       unit_rate_gbp_per_mwh, hedge_price_gbp_per_mwh, hedge_fraction,
       hedged_volume_kwh, unhedged_volume_kwh, revenue_gbp,
       wholesale_cost_gbp, margin_gbp, capital_cost_gbp, net_margin_gbp}
    where capital_cost_gbp = monthly_cost_of_capital_gbp / (periods in that
    calendar month for this term) and net_margin_gbp = margin_gbp - capital_cost_gbp.
    """
    start = date.fromisoformat(term_start_date)
    end = date.fromisoformat(term_end_date)

    price_lookup = {
        (record["settlementDate"], record["settlementPeriod"]): record["systemSellPrice"]
        for record in system_price_records
    }

    records = []
    current_date = start
    while current_date < end:
        date_str = current_date.isoformat()
        shape = consumption_shape(date_str)

        for period in range(1, 49):
            spot_price = price_lookup.get((date_str, period))
            if spot_price is None:
                continue

            consumption_kwh = shape[period - 1]
            if tou_rates is not None:
                peak_rate, offpeak_rate = tou_rates
                period_rate = peak_rate if is_peak_period(date_str, period) else offpeak_rate
            else:
                period_rate = fixed_tariff_rate_gbp_per_mwh
            settled = settle_hedged_period(
                consumption_kwh,
                period_rate,
                hedge_price_gbp_per_mwh,
                hedge_fraction,
                spot_price,
            )

            records.append({
                "customer_id": customer_id,
                "settlement_date": date_str,
                "settlement_period": period,
                "consumption_kwh": consumption_kwh,
                "unit_rate_gbp_per_mwh": period_rate,
                "hedge_price_gbp_per_mwh": hedge_price_gbp_per_mwh,
                "hedge_fraction": hedge_fraction,
                "hedged_volume_kwh": settled["hedged_volume_kwh"],
                "unhedged_volume_kwh": settled["unhedged_volume_kwh"],
                "revenue_gbp": settled["revenue_gbp"],
                "wholesale_cost_gbp": settled["wholesale_cost_gbp"],
                "margin_gbp": settled["margin_gbp"],
            })

        current_date += timedelta(days=1)

    # Capital cost is a term-level figure (collateral is sized once, at term
    # start) but the treasury is debited every period — so allocate it
    # proportionally across whichever periods actually settled in each
    # calendar month this term touches. Grouping by the records that exist
    # (rather than assuming 48/day) absorbs DST's 46/50-period days and any
    # missing-price gaps exactly, with no special-casing.
    records_by_month = defaultdict(list)
    for record in records:
        records_by_month[record["settlement_date"][:7]].append(record)

    for month_records in records_by_month.values():
        capital_cost_per_period_gbp = monthly_cost_of_capital_gbp / len(month_records)
        for record in month_records:
            record["capital_cost_gbp"] = capital_cost_per_period_gbp
            record["net_margin_gbp"] = compute_net_margin(record["margin_gbp"], capital_cost_per_period_gbp)

    return records
