"""Portfolio profit & loss — aggregation of settlement records.

Pure aggregation: takes the flat per-customer-per-period output of
simulation/settlement.py and rolls it up into portfolio totals and a
per-customer breakdown. Doesn't import from sim/ or saas/ — operates only
on the records list it's given (kept pure deliberately, even though it
lives in the orchestration layer, so it's trivial to test and reuse for
any reporting window).

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 0b cross-model
delegation increment. Correct on first generation.
"""


def build_portfolio_pnl(settlement_records: list[dict]) -> dict:
    """Aggregate settlement records into a portfolio P&L summary:

      {
        "portfolio": {consumption_kwh, revenue_gbp, wholesale_cost_gbp,
                      margin_gbp, customer_count},
        "by_customer": {
          "<customer_id>": {consumption_kwh, revenue_gbp,
                            wholesale_cost_gbp, margin_gbp,
                            settlement_period_count},
          ...  # in first-encountered order
        },
      }

    Sums every numeric field exactly (no rounding) in a single pass. An
    empty input returns zeroed/empty structures rather than raising.
    """
    portfolio = {
        "consumption_kwh": 0.0,
        "revenue_gbp": 0.0,
        "wholesale_cost_gbp": 0.0,
        "margin_gbp": 0.0,
        "customer_count": 0,
    }
    by_customer: dict[str, dict] = {}

    for record in settlement_records:
        customer_id = record["customer_id"]

        portfolio["consumption_kwh"] += record["consumption_kwh"]
        portfolio["revenue_gbp"] += record["revenue_gbp"]
        portfolio["wholesale_cost_gbp"] += record["wholesale_cost_gbp"]
        portfolio["margin_gbp"] += record["margin_gbp"]

        if customer_id not in by_customer:
            by_customer[customer_id] = {
                "consumption_kwh": 0.0,
                "revenue_gbp": 0.0,
                "wholesale_cost_gbp": 0.0,
                "margin_gbp": 0.0,
                "settlement_period_count": 0,
            }
            portfolio["customer_count"] += 1

        entry = by_customer[customer_id]
        entry["consumption_kwh"] += record["consumption_kwh"]
        entry["revenue_gbp"] += record["revenue_gbp"]
        entry["wholesale_cost_gbp"] += record["wholesale_cost_gbp"]
        entry["margin_gbp"] += record["margin_gbp"]
        entry["settlement_period_count"] += 1

    return {"portfolio": portfolio, "by_customer": by_customer}
