"""Contract renewal scheduling — Phase 1c renewal increment.

When a customer's 1-year fixed contract ends, they are automatically
renewed at the forward-curve price available on the renewal date (100%
renewal rate assumed; no churn modelled yet — that is a later phase's
concern). This produces a chronological sequence of contiguous, non-
overlapping 1-year contract terms covering the customer's entire tenure,
each independently priced as of its own term-start date.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 1c renewal
increment.
"""

from datetime import date, timedelta

from company.pricing.tariff_engine import CompanyTariffEngine

from saas.tariff_pricing import price_fixed_tariff
from sim.forward_curve import generate_forward_price
from sim.hedging_strategy import MIN_HEDGE_FLOOR
from simulation.policy_costs import (
    get_cm_levy_per_mwh,
    get_fit_levy_per_mwh,
    get_electricity_network_cost_per_mwh,
    get_electricity_policy_cost_per_mwh,
)
from simulation.settlement import CONTRACT_LENGTH_DAYS

_COMPANY_ENGINE = CompanyTariffEngine()

# Phase 34a: company prices the tariff 42 days before term start (statutory notice period).
# The company's forward estimate uses market data observable at notice_date, not at term_start.
# SIM's sim_fwd still uses data up to term_start — it "knows" the real forward.
NOTICE_DAYS = 42


DEEMED_PREMIUM = 0.20  # 20% above spot — UK industry standard for out-of-contract rate
FLEX_MARKUP_PER_MWH = 2.0  # £2/MWh trading desk markup for flex contracts


def build_renewal_schedule(
    customer_id: str, original_acquisition_date: str, report_end_date: str,
    price_records: list[dict], eac_kwh: int, lookback_temps_fn=None,
    segment: str = "resi", tariff_type: str = "fixed",
    deemed_gap_days: int = 0,
) -> list[dict]:
    """Build a chronological sequence of contiguous 1-year contract terms
    for one customer, covering [original_acquisition_date, report_end_date].

    Each term is priced independently as of its own start date: term 1
    starts at original_acquisition_date, term 2 starts exactly
    CONTRACT_LENGTH_DAYS days after term 1 starts (so the terms are
    contiguous and non-overlapping — this exactly matches the active-
    contract window simulation.settlement.run_settlement already enforces),
    and so on until a term's start date is later than report_end_date.

    price_records must already cover every term's pricing lookback window
    (sim.forward_curve.generate_forward_price looks back from each term's
    start date) — the caller is responsible for fetching a wide enough
    range up front; this function does no fetching of its own.

    Returns a flat list of dicts, one per term, in chronological order,
    each shaped exactly like the customer dicts simulation.settlement.run_settlement
    expects (so the returned list can be passed straight into run_settlement,
    one entry per term, all sharing the same customer_id — run_settlement's
    own per-customer 365-day active-window logic will then process each term
    as its own independent contract window):
      {customer_id, acquisition_date, unit_rate_gbp_per_mwh, forward_price_gbp_per_mwh}

    lookback_temps_fn (Phase 4c-3, optional): a callable taking a term's
    start-date string and returning the lookback window's daily mean
    temperatures (or None), passed through to
    `generate_forward_price`'s `lookback_daily_mean_temps_c` for its
    weather-sensitivity multiplier. Defaults to None (no adjustment),
    fully backward compatible.
    """
    term_start = date.fromisoformat(original_acquisition_date)
    report_end = date.fromisoformat(report_end_date)
    terms = []
    first_term = True

    while term_start <= report_end:
        # Phase 40c: insert a deemed gap term before each renewal (except the first).
        # During the gap, the customer is out-of-contract and billed at spot + DEEMED_PREMIUM.
        if deemed_gap_days > 0 and not first_term:
            gap_end = term_start + timedelta(days=deemed_gap_days)
            if gap_end > report_end:
                gap_end = report_end
            terms.append({
                "customer_id": customer_id,
                "acquisition_date": term_start.isoformat(),
                "notice_date": term_start.isoformat(),
                "unit_rate_gbp_per_mwh": None,  # spot-indexed; computed at settlement
                "forward_price_gbp_per_mwh": None,
                "company_forward_price_gbp_per_mwh": None,
                "tariff_type": "deemed",
                "deemed_premium": DEEMED_PREMIUM,
                "term_end": gap_end.isoformat(),
            })
            term_start = gap_end
            if term_start >= report_end:
                break

        first_term = False
        term_start_str = term_start.isoformat()
        # Phase 34a: company prices 42 days before term start; observable data lags by NOTICE_DAYS.
        notice_date = term_start - timedelta(days=NOTICE_DAYS)
        notice_date_str = notice_date.isoformat()
        lookback_temps = lookback_temps_fn(term_start_str) if lookback_temps_fn else None
        # sim_fwd: SIM's sophisticated estimate (used for hedging, risk assessment, weather adj)
        sim_fwd = generate_forward_price(
            term_start_str, price_records, lookback_daily_mean_temps_c=lookback_temps
        )
        # company_fwd: company's observable-data estimate (used for tariff/unit rate).
        # Phase 34a: uses notice_date so the lookback window is anchored 42 days before term start.
        # In a crisis, this means the company priced using pre-spike data — amplifying basis risk.
        try:
            company_fwd = _COMPANY_ENGINE.get_forward_price("electricity", notice_date_str, price_records)
        except ValueError:
            company_fwd = sim_fwd  # fallback: insufficient prior data for first term
        # Phase 30a/31a: CM + FiT levies included in policy_cost pass-through (apply to all segments).
        policy_cost = (
            get_electricity_policy_cost_per_mwh(term_start_str)
            + get_cm_levy_per_mwh(term_start_str)
            + get_fit_levy_per_mwh(term_start_str)
        )
        network_cost = get_electricity_network_cost_per_mwh(term_start_str, segment)
        # Phase 40a: pass-through tariffs lock only wholesale+margin; network and policy
        # are billed at actual rates at settlement (not locked at pricing time).
        # Phase 41a: flex tariffs have no locked unit rate — only the markup is agreed at signing.
        if tariff_type == "flex":
            locked_policy = 0.0
            locked_network = 0.0
        elif tariff_type == "pass_through":
            locked_policy = 0.0
            locked_network = 0.0
        else:
            locked_policy = policy_cost
            locked_network = network_cost
        if tariff_type == "flex":
            # Flex: no locked unit rate. Only markup committed at term start.
            unit_rate = None
        else:
            unit_rate = price_fixed_tariff(
                company_fwd, eac_kwh, term_start_str,
                naked_fraction=1 - MIN_HEDGE_FLOOR,
                policy_cost_per_mwh=locked_policy,
                network_cost_per_mwh=locked_network,
            )
        next_start = term_start + timedelta(days=CONTRACT_LENGTH_DAYS)
        term_dict = {
            "customer_id": customer_id,
            "acquisition_date": term_start_str,
            "notice_date": notice_date_str,
            "unit_rate_gbp_per_mwh": unit_rate,
            "forward_price_gbp_per_mwh": sim_fwd,
            "company_forward_price_gbp_per_mwh": company_fwd,
            "tariff_type": tariff_type,
            "term_end": min(next_start, report_end + timedelta(days=1)).isoformat(),
        }
        if tariff_type == "flex":
            term_dict["flex_markup_per_mwh"] = FLEX_MARKUP_PER_MWH
        terms.append(term_dict)
        term_start = next_start

    return terms
