"""Contract renewal scheduling — Phase 1c renewal increment.

When a customer's 1-year fixed contract ends, they are automatically
renewed at the forward-curve price available on the renewal date (100%
renewal rate assumed; no churn modelled yet — that is a later phase's
concern). This produces a chronological sequence of contiguous, non-
overlapping 1-year contract terms covering the customer's entire tenure,
each independently priced as of its own term-start date.

WHAT THIS MODULE DECIDES, AND WHAT IT ASKS FOR
-----------------------------------------------
KNIFE pass 3, design `B7_renewal_is_a_company_decision`. This module used to run
the company's renewal pricing decision itself — its tariff engine, its pricing
function, its governance escalation and its approval workflow, all imported
straight into the simulated world. It no longer does.

What stays here is the renewal EVENT: the term calendar, the contiguity rule, the
statutory notice period, any deemed gap between terms, the world's own forward
estimate, and the published levy/network schedules for the term. What leaves is
the renewal OFFER — asked for through `company/interfaces/renewal_offer.py` and
received as four numbers. The routine that chose them is not readable from here,
which is the property a real supplier's customers also have.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 1c renewal
increment.
"""

from datetime import date, timedelta

from company.interfaces.renewal_offer import request_renewal_offer
from sim.forward_curve import generate_forward_price
from simulation.household import household_of
from simulation.household_segments import active_renewal_probability_for_customer
from simulation.market_switching_propensity import market_switching_multiplier
from simulation.policy_costs import (
    get_cm_levy_per_mwh,
    get_electricity_network_cost_per_mwh,
    get_electricity_policy_cost_per_mwh,
    get_fit_levy_per_mwh,
)
from simulation.renewal_engagement import rolls_active_renewal
from simulation.settlement import CONTRACT_LENGTH_DAYS
from simulation.svt_product import SVT_TARIFF_TYPE, build_svt_schedule
from simulation.svt_rates import get_svt_elec_rate_gbp_per_mwh

# Phase 34a: company prices the tariff 42 days before term start (statutory notice period).
# The company's forward estimate uses market data observable at notice_date, not at term_start.
# SIM's sim_fwd still uses data up to term_start — it "knows" the real forward.
# This is a WORLD fact (a statutory notice period), which is why it stays here while
# the pricing it triggers moved to the company — see the module docstring.
NOTICE_DAYS = 42


DEEMED_PREMIUM = 0.20  # 20% above spot — UK industry standard for out-of-contract rate
FLEX_MARKUP_PER_MWH = 2.0  # £2/MWh trading desk markup for flex contracts


def build_renewal_schedule(
    customer_id: str, original_acquisition_date: str, report_end_date: str,
    price_records: list[dict], eac_kwh: int, lookback_temps_fn=None,
    segment: str = "resi", tariff_type: str = "fixed",
    deemed_gap_days: int = 0,
) -> list[dict]:
    """Build a chronological sequence of contiguous 1-year contract terms
    for one customer, covering [original_acquisition_date, report_end_date].

    Each term is priced independently as of its own start date: term 1
    starts at original_acquisition_date, term 2 starts exactly
    CONTRACT_LENGTH_DAYS days after term 1 starts (so the terms are
    contiguous and non-overlapping — this exactly matches the active-
    contract window simulation.settlement.run_settlement already enforces),
    and so on until a term's start date is later than report_end_date.

    price_records must already cover every term's pricing lookback window
    (sim.forward_curve.generate_forward_price looks back from each term's
    start date) — the caller is responsible for fetching a wide enough
    range up front; this function does no fetching of its own.

    Returns a flat list of dicts, one per term, in chronological order,
    each shaped exactly like the customer dicts simulation.settlement.run_settlement
    expects (so the returned list can be passed straight into run_settlement,
    one entry per term, all sharing the same customer_id — run_settlement's
    own per-customer 365-day active-window logic will then process each term
    as its own independent contract window):
      {customer_id, acquisition_date, unit_rate_gbp_per_mwh, forward_price_gbp_per_mwh}

    lookback_temps_fn (Phase 4c-3, optional): a callable taking a term's
    start-date string and returning the lookback window's daily mean
    temperatures (or None), passed through to
    `generate_forward_price`'s `lookback_daily_mean_temps_c` for its
    weather-sensitivity multiplier. Defaults to None (no adjustment),
    fully backward compatible.
    """
    # A STANDARD VARIABLE TARIFF IS NOT A TERM, so it is not built by a loop over terms.
    # Everything below this line assumes a contract that ends: a 42-day notice date, a price
    # struck through `request_renewal_offer`, a `prev_fixed_unit_rate` locked for the next
    # boundary, and a renewal decision at each one. An SVT has none of those -- its price
    # changes on the cap's calendar and the household is never asked. Delegated rather than
    # branched, because a fourth `tariff_type` inside this loop would put a no-renewal product
    # in a loop every line of which is about a renewal. See simulation/svt_product.py, and
    # `docs/design/DRAWN_BOOK_TARIFF_TYPE_FIDELITY_DETERMINATION.md` for why the world owed one.
    if tariff_type == SVT_TARIFF_TYPE:
        return build_svt_schedule(
            customer_id, original_acquisition_date, report_end_date, price_records,
            lookback_temps_fn=lookback_temps_fn,
        )

    term_start = date.fromisoformat(original_acquisition_date)
    report_end = date.fromisoformat(report_end_date)
    terms = []
    first_term = True
    # The rate this customer is on today — a fact of the contract the world holds,
    # handed back to the company with each renewal request. The company uses it to
    # classify the move as routine or not; that classification is not made here and
    # is not visible here. None until the first fixed term is priced.
    prev_fixed_unit_rate: float | None = None

    while term_start <= report_end:
        # ═══════════════════════════════════════════════════════════════════════════════════
        # C1b — THE WORLD ALREADY DECIDED THIS, AND USED TO THROW THE ANSWER AWAY (2026-08-30)
        # ═══════════════════════════════════════════════════════════════════════════════════
        #
        # `rolls_active_renewal` has been called at every electricity renewal since Phase 33 and
        # returns, in its own docstring's words, "False if a passive SVT roll". The answer reached
        # `event["is_active_renewal"]`, was written to the log, and then the world built the
        # household another fixed term anyway. So the world both knew who had rolled onto the
        # standard variable tariff and settled them as though nobody had.
        #
        # NO NEW RULE AND NO NEW CONSTANT. Same function, same seed grammar
        # (`{household}_{term_index}`, and `len(terms)` is that index because `run_phase2b`
        # counts every term this builder appends), same per-household engagement archetype and
        # the same anchored 35% population rate. The crisis forcing comes along and is the reason
        # the generated fixed share collapses in 2022, which is what the published record does
        # too. THAT FORCING IS NO LONGER A CALENDAR YEAR: 2026-09-04 replaced
        # `CRISIS_PASSIVE_YEARS = {"2022"}` with `renewal_engagement.FTC_WITHDRAWAL_WINDOW`,
        # ending 2023-06-30 on Ofgem's own "re-emergence of FTCs in the second half of 2023".
        # A stint forced at the end of that window runs to the household's next anniversary, so
        # the withdrawal's effect reaches into H1 2024 without anything here saying 2024.
        #
        # WHY A PASSIVE STINT IS BOUNDED BY THE ANNIVERSARY AND NOT ABSORBING. An SVT has no term
        # and this does not give it one: no notice is served, no rate is struck and no offer is
        # made for the whole stint (`build_svt_schedule` prices every segment off the published
        # cap). What the anniversary marks is the HOUSEHOLD's own next look at the market, on the
        # cadence the world already uses for one. Making SVT absorbing instead was the first
        # draft and the published split refutes it: with no route back, the fixed share decays to
        # 12% by the second renewal and to nothing after 2022, against a published domestic fixed
        # share that is a minority in every year of the window but never vanishes and is ~33% in
        # 2025 (`docs/design/DRAWN_BOOK_TARIFF_TYPE_FIDELITY_DETERMINATION.md` §(b)).
        #
        # DOMESTIC ONLY, because the product is. `simulation/svt_rates.py` is the Ofgem DOMESTIC
        # default-tariff cap; an SME or I&C site has no default tariff to roll onto and its
        # renewals are broker-driven, which `run_phase2b` already states at its own passive
        # branch. That is the published scope of the anchor, not a carve-out chosen here.
        if not first_term and tariff_type == "fixed" and segment == "resi":
            _household = household_of(customer_id)
            _anniversary = term_start + timedelta(days=CONTRACT_LENGTH_DAYS)
            if not rolls_active_renewal(
                term_start.isoformat(),
                f"{_household}_{len(terms)}",
                active_renewal_probability_for_customer(_household),
            ):
                terms.extend(build_svt_schedule(
                    customer_id,
                    term_start.isoformat(),
                    min(_anniversary - timedelta(days=1), report_end).isoformat(),
                    price_records,
                    lookback_temps_fn=lookback_temps_fn,
                ))
                # The rate this household is on is now the cap, and the cap is not a struck
                # price. Clearing the lock stops the next fixed offer being classified against a
                # rate the company never set, which is what `prior_fixed_unit_rate` is for.
                prev_fixed_unit_rate = None
                term_start = _anniversary
                continue

        # Phase 40c: insert a deemed gap term before each renewal (except the first).
        # During the gap, the customer is out-of-contract and billed at spot + DEEMED_PREMIUM.
        if deemed_gap_days > 0 and not first_term:
            gap_end = term_start + timedelta(days=deemed_gap_days)
            if gap_end > report_end:
                gap_end = report_end
            terms.append({
                "customer_id": customer_id,
                "acquisition_date": term_start.isoformat(),
                "notice_date": term_start.isoformat(),
                "unit_rate_gbp_per_mwh": None,  # spot-indexed; computed at settlement
                "forward_price_gbp_per_mwh": None,
                "company_forward_price_gbp_per_mwh": None,
                "tariff_type": "deemed",
                "deemed_premium": DEEMED_PREMIUM,
                "term_end": gap_end.isoformat(),
            })
            term_start = gap_end
            if term_start >= report_end:
                break

        first_term = False
        term_start_str = term_start.isoformat()
        # Phase 34a: company prices 42 days before term start; observable data lags by NOTICE_DAYS.
        notice_date = term_start - timedelta(days=NOTICE_DAYS)
        notice_date_str = notice_date.isoformat()
        lookback_temps = lookback_temps_fn(term_start_str) if lookback_temps_fn else None
        # sim_fwd: SIM's sophisticated estimate (used for hedging, risk assessment, weather adj)
        sim_fwd = generate_forward_price(
            term_start_str, price_records, lookback_daily_mean_temps_c=lookback_temps
        )
        # Phase 30a/31a: CM + FiT levies included in policy_cost pass-through (apply to all segments).
        # PUBLISHED schedules — what any market participant can look up for this term.
        policy_cost = (
            get_electricity_policy_cost_per_mwh(term_start_str)
            + get_cm_levy_per_mwh(term_start_str)
            + get_fit_levy_per_mwh(term_start_str)
        )
        network_cost = get_electricity_network_cost_per_mwh(term_start_str, segment)
        # B4_competitor_field (2026-08-24): two more published figures, handed
        # over the same way as policy_cost/network_cost above -- the Ofgem
        # domestic default-tariff cap (None before 2016, where no data exists)
        # and the published aggregate market-savings signal for the term's
        # year (docs/design/simplifications/B4_competitor_field.yaml).
        svt_gbp_per_mwh = get_svt_elec_rate_gbp_per_mwh(term_start_str)
        switching_multiplier = market_switching_multiplier(term_start.year)
        # KNIFE pass 3, B7_renewal_is_a_company_decision: the world serves notice and
        # then ASKS. What comes back is an offer — a rate, the forward the company
        # priced off, and the two cost components it chose to lock. Which forward it
        # used, what it locks for this product, how it priced, and whether the move
        # needed an approval are all decided behind the door and are no longer
        # visible from here: see company/interfaces/renewal_offer.py.
        offer = request_renewal_offer(
            customer_id=customer_id,
            term_start=term_start,
            notice_date=notice_date,
            tariff_type=tariff_type,
            segment=segment,
            eac_kwh=eac_kwh,
            observable_price_records=price_records,
            published_policy_cost_per_mwh=policy_cost,
            published_network_cost_per_mwh=network_cost,
            prior_fixed_unit_rate=prev_fixed_unit_rate,
            # The world's own estimate, handed over for the cold-start case where
            # the company's notice-date lookback window is empty. A named leak, not
            # an oversight — register §3a records it as owed.
            fallback_forward_price_gbp_per_mwh=sim_fwd,
            published_svt_gbp_per_mwh=svt_gbp_per_mwh,
            published_market_switching_multiplier=switching_multiplier,
        )
        company_fwd = offer.company_forward_price_gbp_per_mwh
        unit_rate = offer.unit_rate_gbp_per_mwh
        if tariff_type != "flex":
            prev_fixed_unit_rate = unit_rate
        next_start = term_start + timedelta(days=CONTRACT_LENGTH_DAYS)
        term_dict = {
            "customer_id": customer_id,
            "acquisition_date": term_start_str,
            "notice_date": notice_date_str,
            "unit_rate_gbp_per_mwh": unit_rate,
            "forward_price_gbp_per_mwh": sim_fwd,
            "company_forward_price_gbp_per_mwh": company_fwd,
            "tariff_type": tariff_type,
            "term_end": min(next_start, report_end + timedelta(days=1)).isoformat(),
        }
        if tariff_type == "flex":
            term_dict["flex_markup_per_mwh"] = FLEX_MARKUP_PER_MWH
        terms.append(term_dict)
        term_start = next_start

    return terms
