"""Contract renewal scheduling — Phase 1c renewal increment.

When a customer's 1-year fixed contract ends, they are automatically
renewed at the forward-curve price available on the renewal date (100%
renewal rate assumed; no churn modelled yet — that is a later phase's
concern). This produces a chronological sequence of contiguous, non-
overlapping 1-year contract terms covering the customer's entire tenure,
each independently priced as of its own term-start date.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 1c renewal
increment.
"""

from datetime import date, timedelta

from saas.tariff_pricing import price_fixed_tariff
from sim.forward_curve import generate_forward_price
from simulation.settlement import CONTRACT_LENGTH_DAYS


def build_renewal_schedule(customer_id: str, original_acquisition_date: str, report_end_date: str, price_records: list[dict], eac_kwh: int) -> list[dict]:
    """Build a chronological sequence of contiguous 1-year contract terms
    for one customer, covering [original_acquisition_date, report_end_date].

    Each term is priced independently as of its own start date: term 1
    starts at original_acquisition_date, term 2 starts exactly
    CONTRACT_LENGTH_DAYS days after term 1 starts (so the terms are
    contiguous and non-overlapping — this exactly matches the active-
    contract window simulation.settlement.run_settlement already enforces),
    and so on until a term's start date is later than report_end_date.

    price_records must already cover every term's pricing lookback window
    (sim.forward_curve.generate_forward_price looks back from each term's
    start date) — the caller is responsible for fetching a wide enough
    range up front; this function does no fetching of its own.

    Returns a flat list of dicts, one per term, in chronological order,
    each shaped exactly like the customer dicts simulation.settlement.run_settlement
    expects (so the returned list can be passed straight into run_settlement,
    one entry per term, all sharing the same customer_id — run_settlement's
    own per-customer 365-day active-window logic will then process each term
    as its own independent contract window):
      {customer_id, acquisition_date, unit_rate_gbp_per_mwh, forward_price_gbp_per_mwh}
    """
    term_start = date.fromisoformat(original_acquisition_date)
    report_end = date.fromisoformat(report_end_date)
    terms = []

    while term_start <= report_end:
        term_start_str = term_start.isoformat()
        forward_price = generate_forward_price(term_start_str, price_records)
        unit_rate = price_fixed_tariff(forward_price, eac_kwh, term_start_str)
        terms.append({
            "customer_id": customer_id,
            "acquisition_date": term_start_str,
            "unit_rate_gbp_per_mwh": unit_rate,
            "forward_price_gbp_per_mwh": forward_price
        })
        term_start += timedelta(days=CONTRACT_LENGTH_DAYS)

    return terms
