"""Phase 1d: agent-discovered, time-evolving hedging strategy.

Builds an agent that decides its own hedge position at each contract
acquisition/renewal and evolves it over time — using only information it
could actually have at each decision point. No pre-set strategies are
compared; the agent controls exactly one lever (hedge_fraction — see
sim/hedging_strategy.py) and learns its way to a position purely from its
own realised, completed-term history.

Why tenor is held fixed at 12 months (the "annual strip"): the backlog's
instrument menu spans day-ahead through Cal+1, but blending several
overlapping sub-term positions inside a single contract year would mean
tracking nested hedge books and would materially complicate the settlement
loop — for a benefit that doesn't change the question Phase 1d is actually
testing: does locking in price ahead of delivery protect margin when spot
runs hot, and does an agent that watches its own results adjust that
lock-in ratio sensibly? One instrument — the annual strip, matched 1:1 to
the contract term, priced at exactly the same forward price that sets the
customer's tariff (sim.forward_curve.generate_forward_price via the
existing renewal schedule) — isolates that question cleanly. Multi-tenor
blending is a natural extension once this single-lever model is validated.

Renewals are active throughout (Rich's Phase 1c gate answer — 100% renewal
rate, no churn): simulation.renewals.build_renewal_schedule supplies each
customer's full chronological sequence of independently-priced contract
terms, and the agent makes one fresh hedging decision at the start of each.

No foresight, structurally not just by convention: each term is settled by
simulation.hedged_settlement.run_hedged_term in isolation — a function that
has no way to see beyond the one term it's asked to settle — and the agent
only gets to call sim.hedging_strategy.evolve_hedge_fraction once that
term's full outcome (every period, every real spot price) is known. The
sequencing in run_customer_book is what makes "decide, then observe, then
adjust" true in code, not just in prose.

Hedge effectiveness is measured against a naked counterfactual: for every
settled period we also compute what margin a 100%-spot-exposure book would
have produced from the exact same consumption, tariff revenue, and real
spot price (this is also the PiT-safe signal sim.hedging_strategy uses to
evolve). Comparing actual vs. naked margin year by year is what answers the
backlog's question — did the agent's evolving position help in the crisis
years (2021-2022) versus the stable years either side of them?

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 1d hedging
increment.
"""

from datetime import date, timedelta
from collections import defaultdict

from sim.profile_class_1 import load_pc1_shape
from sim.system_prices_history import get_system_prices_range
from sim.hedging_strategy import decide_initial_hedge_fraction, evolve_hedge_fraction
from simulation.renewals import build_renewal_schedule
from simulation.hedged_settlement import run_hedged_term
from simulation.settlement import CONTRACT_LENGTH_DAYS
from simulation.portfolio_pnl import build_portfolio_pnl
from saas.customers import CUSTOMERS, customer_to_settlement_input

REPORT_START = "2016-01-01"
REPORT_END = "2025-06-07"

CRISIS_YEARS = {"2021", "2022"}


def run_customer_book(customer_id: str, schedule: list[dict], price_lookup: dict, price_records: list[dict]):
    """Run one customer's full renewal-aware tenure through the agent's
    hedging strategy, term by term, in strict chronological order.

    For each term: settle it at the CURRENTLY-decided hedge_fraction (the
    agent cannot know that term's outcome before settling it), then —
    and only then — observe its actual margin against the naked
    counterfactual and call evolve_hedge_fraction to set the fraction the
    NEXT term will be settled at. This loop is the literal implementation
    of "decide, observe, adjust, repeat" — there is no path through this
    code by which a later term's data could influence an earlier decision.

    Returns (settlement_records, initial_reasoning, evolution_log) where
    evolution_log is a chronological list of per-term audit entries:
      {term_index, term_start, hedge_price_gbp_per_mwh, hedge_fraction_used,
       actual_margin_gbp, naked_margin_gbp, evolution_reasoning,
       next_hedge_fraction}
    """
    hedge_fraction, initial_reasoning = decide_initial_hedge_fraction()

    all_records = []
    evolution_log = []

    for term_index, term in enumerate(schedule):
        term_start = term["acquisition_date"]
        term_end = (date.fromisoformat(term_start) + timedelta(days=CONTRACT_LENGTH_DAYS)).isoformat()
        if term_end > REPORT_END:
            term_end = (date.fromisoformat(REPORT_END) + timedelta(days=1)).isoformat()

        term_records = run_hedged_term(
            customer_id,
            term_start,
            term_end,
            term["unit_rate_gbp_per_mwh"],
            term["forward_price_gbp_per_mwh"],
            hedge_fraction,
            load_pc1_shape,
            price_records,
        )
        all_records.extend(term_records)

        actual_margin_gbp = sum(record["margin_gbp"] for record in term_records)
        naked_margin_gbp = sum(
            record["revenue_gbp"] - (record["consumption_kwh"] / 1000) * price_lookup[(record["settlement_date"], record["settlement_period"])]
            for record in term_records
        )

        new_hedge_fraction, evolution_reasoning = evolve_hedge_fraction(hedge_fraction, naked_margin_gbp, actual_margin_gbp)

        evolution_log.append({
            "term_index": term_index,
            "term_start": term_start,
            "hedge_price_gbp_per_mwh": term["forward_price_gbp_per_mwh"],
            "hedge_fraction_used": hedge_fraction,
            "actual_margin_gbp": actual_margin_gbp,
            "naked_margin_gbp": naked_margin_gbp,
            "evolution_reasoning": evolution_reasoning,
            "next_hedge_fraction": new_hedge_fraction,
        })

        hedge_fraction = new_hedge_fraction

    return all_records, initial_reasoning, evolution_log


def main():
    # One fetch wide enough for every term's pricing lookback AND the full
    # settlement window — exactly the strategy proven in run_phase1c_renewals.
    earliest_acquisition = min(date.fromisoformat(c["acquisition_date"]) for c in CUSTOMERS)
    fetch_start = (earliest_acquisition - timedelta(days=90)).isoformat()
    price_records = get_system_prices_range(fetch_start, REPORT_END)
    print(f"Retrieved {len(price_records)} SSP records for {fetch_start} to {REPORT_END} (lookback + settlement window, fetched once).")

    price_lookup = {
        (record["settlementDate"], record["settlementPeriod"]): record["systemSellPrice"]
        for record in price_records
    }

    all_records = []
    print("\n=== Agent hedging decisions, term by term ===")
    for customer in CUSTOMERS:
        settlement_input = customer_to_settlement_input(customer)
        customer_id = settlement_input["customer_id"]
        schedule = build_renewal_schedule(customer_id, settlement_input["acquisition_date"], REPORT_END, price_records)

        customer_records, initial_reasoning, evolution_log = run_customer_book(customer_id, schedule, price_lookup, price_records)
        all_records.extend(customer_records)

        print(f"\n{customer_id} — initial decision: hedge_fraction = {evolution_log[0]['hedge_fraction_used']:.2f}")
        print(f"  reasoning: {initial_reasoning}")
        for entry in evolution_log:
            print(
                f"  term {entry['term_index']} (starts {entry['term_start']}): "
                f"hedge_fraction={entry['hedge_fraction_used']:.2f} "
                f"hedge_price=£{entry['hedge_price_gbp_per_mwh']:.2f}/MWh -> "
                f"actual_margin=£{entry['actual_margin_gbp']:.2f} "
                f"naked_margin=£{entry['naked_margin_gbp']:.2f}"
            )
            print(f"    evolution: {entry['evolution_reasoning']}")

    # Add the naked-counterfactual margin to every settled period so the
    # year-by-year hedge-effectiveness comparison can be built in one pass —
    # the same comparison the agent itself uses to evolve, just rolled up
    # by calendar year instead of by contract term.
    for record in all_records:
        spot_price = price_lookup[(record["settlement_date"], record["settlement_period"])]
        record["naked_margin_gbp"] = record["revenue_gbp"] - (record["consumption_kwh"] / 1000) * spot_price

    print(f"\nProduced {len(all_records)} hedge-aware settlement records across {len(CUSTOMERS)} customers.")

    # Portfolio P&L by calendar year (actual, hedge-aware economics)
    yearly_settlements = defaultdict(list)
    for record in all_records:
        yearly_settlements[record["settlement_date"][:4]].append(record)

    print("\n=== Portfolio P&L by calendar year (agent's actual hedge-aware economics) ===")
    for year in sorted(yearly_settlements.keys()):
        yearly_pnl = build_portfolio_pnl(yearly_settlements[year])
        flag = "  <- crisis year" if year in CRISIS_YEARS else ""
        print(
            f"  {year}: customers={yearly_pnl['portfolio']['customer_count']} "
            f"consumption={yearly_pnl['portfolio']['consumption_kwh']:.2f} kWh "
            f"revenue=£{yearly_pnl['portfolio']['revenue_gbp']:.2f} "
            f"cost=£{yearly_pnl['portfolio']['wholesale_cost_gbp']:.2f} "
            f"margin=£{yearly_pnl['portfolio']['margin_gbp']:.2f}{flag}"
        )

    # Hedge effectiveness: actual (agent) vs naked-counterfactual margin, by year
    print("\n=== Hedge effectiveness: agent's actual margin vs. naked (100% spot) counterfactual, by calendar year ===")
    crisis_actual = crisis_naked = stable_actual = stable_naked = 0.0
    for year in sorted(yearly_settlements.keys()):
        year_records = yearly_settlements[year]
        actual = sum(r["margin_gbp"] for r in year_records)
        naked = sum(r["naked_margin_gbp"] for r in year_records)
        difference = actual - naked
        flag = "  <- crisis year" if year in CRISIS_YEARS else ""
        verdict = "agent beat naked" if difference > 0 else ("naked would have won" if difference < 0 else "tied")
        print(
            f"  {year}: actual=£{actual:.2f} naked=£{naked:.2f} "
            f"difference=£{difference:+.2f} ({verdict}){flag}"
        )
        if year in CRISIS_YEARS:
            crisis_actual += actual
            crisis_naked += naked
        else:
            stable_actual += actual
            stable_naked += naked

    print(f"\n  Crisis years (2021-2022) combined: actual=£{crisis_actual:.2f} naked=£{crisis_naked:.2f} difference=£{crisis_actual - crisis_naked:+.2f}")
    print(f"  Stable years (everything else) combined: actual=£{stable_actual:.2f} naked=£{stable_naked:.2f} difference=£{stable_actual - stable_naked:+.2f}")

    # Full-window portfolio P&L and per-customer breakdown
    pnl = build_portfolio_pnl(all_records)
    print(f"\n=== Portfolio P&L for the full window {REPORT_START} to {REPORT_END} ===")
    print(f"Active Customer Count: {pnl['portfolio']['customer_count']}")
    print(f"Consumption (kWh): {pnl['portfolio']['consumption_kwh']:0.2f}")
    print(f"Revenue (£): £{pnl['portfolio']['revenue_gbp']:0.2f}")
    print(f"Wholesale Cost (£): £{pnl['portfolio']['wholesale_cost_gbp']:0.2f}")
    print(f"Margin (£): £{pnl['portfolio']['margin_gbp']:0.2f}")

    print("\nPer-Customer Breakdown:")
    for customer_id, customer_data in pnl["by_customer"].items():
        print(f"Customer ID: {customer_id}, Settlement Period Count: {customer_data['settlement_period_count']}")
        print(f"Consumption (kWh): {customer_data['consumption_kwh']:0.2f}")
        print(f"Revenue (£): £{customer_data['revenue_gbp']:0.2f}")
        print(f"Cost (£): £{customer_data['wholesale_cost_gbp']:0.2f}")
        print(f"Margin (£): £{customer_data['margin_gbp']:0.2f}\n")

    return {"pnl": pnl, "settlement_records": all_records}


if __name__ == "__main__":
    main()
