"""Per-customer, per-settlement-period settlement run.

Combines consumption (sim/profile_class_1.py — Profile Class 1 shape),
contract pricing (saas/tariff_pricing.py — fixed unit rate set at
acquisition), and real wholesale spot prices (sim/system_prices_history.py
— System Sell Price) into one settlement record per active customer per
half-hourly period. This is the orchestration layer's job, not sim/'s or
saas/'s — see simulation/README.md for why code here is allowed to see
both sides of the seam.

Generated by qwen2.5-coder:14b (local, via tools/delegate_ollama.py) and
reviewed/integrated by the frontier orchestrator — Phase 0b cross-model
delegation increment. Verified correct on first generation (cross-checked
record counts and a manual per-period calculation against real 2016-10 to
2016-12 data) — unlike the profile-shape date logic, this one needed no
correction round.
"""

from datetime import date, timedelta

CONTRACT_LENGTH_DAYS = 365


def run_settlement(
    customers: list[dict],
    start_date: str,
    end_date: str,
    consumption_shape,
    system_price_records: list[dict],
) -> list[dict]:
    """Run settlement for every customer, for every calendar date in
    [start_date, end_date] inclusive, for every settlement period (1-48) —
    but only for (customer, date) combinations where the customer is on an
    active 1-year fixed contract on that date: acquisition_date <= date <
    acquisition_date + 365 days.

    Each customer is a dict {"customer_id", "acquisition_date"
    ('YYYY-MM-DD'), "unit_rate_gbp_per_mwh"}. consumption_shape(date_str)
    returns 48 kWh floats indexed 0..47 for settlement periods 1..48.
    system_price_records supplies the real System Sell Price (£/MWh) used
    as the wholesale cost reference, looked up by exact (settlementDate,
    settlementPeriod) match — periods with no matching price record are
    skipped, not guessed.

    Returns a flat list of records (customer, then chronological date, then
    settlement period 1..48), each:
      {customer_id, settlement_date, settlement_period, consumption_kwh,
       unit_rate_gbp_per_mwh, revenue_gbp, wholesale_cost_gbp, margin_gbp}
    where (converting kWh to MWh by /1000):
      revenue_gbp = consumption_kwh/1000 * unit_rate_gbp_per_mwh
      wholesale_cost_gbp = consumption_kwh/1000 * system_sell_price
      margin_gbp = revenue_gbp - wholesale_cost_gbp
    """
    start = date.fromisoformat(start_date)
    end = date.fromisoformat(end_date)

    price_lookup = {
        (record["settlementDate"], record["settlementPeriod"]): record["systemSellPrice"]
        for record in system_price_records
    }

    records = []
    for customer in customers:
        acquisition_date = date.fromisoformat(customer["acquisition_date"])
        contract_end = acquisition_date + timedelta(days=CONTRACT_LENGTH_DAYS)
        unit_rate = customer["unit_rate_gbp_per_mwh"]

        current_date = start
        while current_date <= end:
            if acquisition_date <= current_date < contract_end:
                date_str = current_date.isoformat()
                shape = consumption_shape(date_str)

                for period in range(1, 49):
                    price = price_lookup.get((date_str, period))
                    if price is None:
                        continue

                    consumption_kwh = shape[period - 1]
                    revenue_gbp = (consumption_kwh / 1000) * unit_rate
                    wholesale_cost_gbp = (consumption_kwh / 1000) * price

                    records.append({
                        "customer_id": customer["customer_id"],
                        "settlement_date": date_str,
                        "settlement_period": period,
                        "consumption_kwh": consumption_kwh,
                        "unit_rate_gbp_per_mwh": unit_rate,
                        "revenue_gbp": revenue_gbp,
                        "wholesale_cost_gbp": wholesale_cost_gbp,
                        "margin_gbp": revenue_gbp - wholesale_cost_gbp,
                    })

            current_date += timedelta(days=1)

    return records
