"""R15 coverage for the undischarged credit-balance control.

The named defect this control exists for is REAL and is in the committed ledger: C7
invoice 841 (issued 2018-08-01) is a multi-hundred-pound catch-up credit note, and the
account's settled balance then sits at that floor for years -- with every payment
returning it to the floor rather than drawing it down. The control must FIRE on that.
The pre-existing footing control (`check_billed_clock_reconciles`) passes on the same
data, which is the blindness being closed.

NOTE ON WHAT IS ASSERTED HERE (2026-08-08): `docs/state/billing_ledger.json` is
REGENERATED by every sim run, so the credit's exact pence value moves (it was -201.96
when this was written and -202.27 one run later, which wedged the publish gate). This
test therefore asserts the SHAPE of the defect -- a material, multi-year, undischarged
CREDIT that the control fires on -- never a pinned generated figure. The control's
fires/does-not-fire proof rests on the synthetic fixtures below, which are fixed by
construction and are the real R15 evidence.

AND THE ACCOUNT LABEL IS A GENERATED FIGURE TOO (2026-08-30). The 2026-08-08 repair took
the pence off the pin and left `C7` on it, which is the same mistake one level up: the
book is re-drawn, so `C7` names a different household from one run to the next. It now
holds 24 invoices, none of them negative, and its book ends 2017-12-30 -- it never
reaches the 2018-08-01 catch-up credit this file was written about. That wedged the
publish gate for a second time, and it wedged it by asserting a REGENERATED IDENTITY.

So the live-data arm is now keyed to the PROPERTY: it searches the whole book for the
class of defect and takes the worst instance, whatever it is called this run. Measured
at the time of writing, 27 of 251 accounts carry one (worst: SYN-2016-016, 2807 days,
-£1508.66) -- the class is abundant, it was only C7 that moved.

WHY A SKIP AND NOT A FAILURE WHEN THE BOOK IS CLEAN. A book with no undischarged credit
in it is the billing model being RIGHT. A test that went red on that would be asserting
the model stays bad -- keyed to today's answer, green while the claim rots, exactly
backwards. The detection power of the control is proven by the synthetic fixtures below,
which are fixed by construction; this arm's job is narrower and is about two controls,
not about the book: that on a REAL instance the new control fires where the old footing
control is blind. With no real instance there is nothing to say, and saying so out loud
is the honest result.
"""
from __future__ import annotations

import json
import pathlib

import pytest

from company.billing.credit_balance_control import (
    check_credit_balance_discharged,
    longest_undischarged_credit,
    settled_balance_series,
)
from company.compliance.domain_invariants import check_billed_clock_reconciles

LEDGER = pathlib.Path(__file__).resolve().parents[3] / "docs" / "state" / "billing_ledger.json"


#: What makes a real credit worth a control's attention: held over a year, and material
#: rather than a rounding artefact. These are the SHAPE thresholds the 2026-08-08 repair
#: introduced -- they are properties of the defect class, not measurements of this book.
_MULTI_YEAR_DAYS = 365
_MATERIAL_FLOOR_GBP = -50


def _worst_real_undischarged_credit():
    """(account_id, account, worst) for the book's worst undischarged credit, or None.

    Deterministic across runs that re-draw the book: ordered by the floor (most negative
    first) and tie-broken on the account id, so two tests selecting independently are
    guaranteed to be talking about the SAME account. That mattered here -- the pair below
    only says anything if both controls are asked about one subject.
    """
    d = json.loads(LEDGER.read_text())
    found = []
    for account_id, account in d["customers"].items():
        worst = longest_undischarged_credit(account.get("invoices"), account.get("payments"))
        if (worst is not None
                and worst["days"] > _MULTI_YEAR_DAYS
                and worst["floor_gbp"] < _MATERIAL_FLOOR_GBP):
            found.append((worst["floor_gbp"], account_id, account, worst))
    if not found:
        return None
    floor_gbp, account_id, account, worst = min(found)
    return account_id, account, worst


def _require_a_real_instance():
    selected = _worst_real_undischarged_credit()
    if selected is None:
        pytest.skip(
            "the regenerated book currently holds no material multi-year undischarged "
            "credit, so there is no real instance for this arm to be about. This is a "
            "PASS for the billing model, not a gap in the control: its fires/does-not-"
            "fire proof is the synthetic fixtures below, which are fixed by construction."
        )
    return selected


# ── the control FIRES on the real defect, wherever the book put it this run ──────────
@pytest.mark.skipif(not LEDGER.is_file(), reason="billing ledger snapshot not present")
def test_fires_on_the_real_undischarged_credit_in_the_book():
    account_id, account, worst = _require_a_real_instance()
    # The selector already applied the shape thresholds, so re-asserting them here would
    # be a tautology. What is NOT guaranteed by selection is that the control's own
    # verdict agrees with its own detector -- that is the assertion worth making.
    assert check_credit_balance_discharged(
        account["invoices"], account["payments"], discharge_events=None) is False, (
        f"{account_id} holds a {worst['floor_gbp']} credit for {worst['days']} days with "
        "no refund recorded, and the control did not fire on it"
    )


@pytest.mark.skipif(not LEDGER.is_file(), reason="billing ledger snapshot not present")
def test_the_old_footing_control_passes_on_the_same_data():
    """The point of the new control: the existing one is BLIND here, because the credit
    note nets into both sides of the footing identically. This is not a criticism of
    that control -- it is why a second, lifecycle-shaped control was needed."""
    account_id, account, worst = _require_a_real_instance()
    total_billed = round(sum(i["total_amount_gbp"] for i in account["invoices"]), 2)
    assert check_billed_clock_reconciles(total_billed, account["invoices"]) is True, (
        f"the footing control fired on {account_id} too, so this pair no longer "
        "demonstrates the blindness it exists to demonstrate"
    )


# ── it must NOT fire on the healthy cases (or it becomes noise and gets muted) ───────
def _inv(n, d, amt):
    return {"invoice_number": n, "issue_date": d, "total_amount_gbp": amt}


def _pay(n, d, amt, outcome="success"):
    return {"invoice_number": n, "payment_date": d, "amount_gbp": amt, "outcome": outcome}


def test_silent_on_an_account_that_always_settles_to_zero():
    inv = [_inv(1, "2020-01-01", 100.0), _inv(2, "2020-02-01", 100.0)]
    pay = [_pay(1, "2020-01-15", 100.0), _pay(2, "2020-02-15", 100.0)]
    assert check_credit_balance_discharged(inv, pay, discharge_events=None) is True
    assert longest_undischarged_credit(inv, pay) is None


def test_silent_on_sub_materiality_rounding_credit():
    """C7 invoice 900 is a real -£0.22 credit note. Pennies are not a refund case."""
    inv = [_inv(1, "2020-01-01", 100.0), _inv(2, "2020-02-01", -0.22)]
    pay = [_pay(1, "2020-01-15", 100.0), _pay(2, "2024-02-15", 0.0)]
    assert check_credit_balance_discharged(inv, pay, discharge_events=None) is True


def test_silent_when_the_credit_is_offset_within_the_year():
    """Credit raised, then consumed by later bills -- the ordinary discharge path."""
    inv = [_inv(1, "2020-01-01", -50.0), _inv(2, "2020-03-01", 50.0)]
    pay = [_pay(1, "2020-01-15", 0.0), _pay(2, "2020-03-15", 0.0)]
    assert check_credit_balance_discharged(inv, pay, discharge_events=None) is True


def test_silent_when_held_long_but_a_refund_IS_recorded():
    inv = [_inv(1, "2018-08-01", -200.0), _inv(2, "2021-01-01", 100.0)]
    pay = [_pay(1, "2018-08-15", 0.0), _pay(2, "2021-01-15", 100.0)]
    assert check_credit_balance_discharged(inv, pay, discharge_events=None) is False
    assert check_credit_balance_discharged(
        inv, pay, discharge_events=[{"trigger": "customer_request"}]) is True


# ── FAIL-CLOSED: an unavailable check is a FAILED check ─────────────────────────────
@pytest.mark.parametrize("invoices,payments", [
    (None, []),
    ([], None),
    ([{"issue_date": "2020-01-01"}], []),                        # missing amount
    ([{"issue_date": "not-a-date", "total_amount_gbp": 1.0}], []),
    ([{"issue_date": "2020-01-01", "total_amount_gbp": "12.00"}], []),   # string amount
])
def test_fails_closed_on_missing_or_malformed_input(invoices, payments):
    assert check_credit_balance_discharged(invoices, payments, discharge_events=None) is False


def test_bool_is_not_accepted_as_an_amount():
    """bool is a subclass of int in Python -- a True that reached the arithmetic would
    silently count as £1. Fail closed instead."""
    inv = [{"issue_date": "2020-01-01", "total_amount_gbp": True}]
    assert settled_balance_series(inv, []) is None


# ── independence (anti-TAUTOLOGY): the control never reads the netted aggregates ─────
def test_does_not_consult_the_ledgers_own_netted_totals():
    """The blindness being fixed lives in the netted aggregates, so the control rebuilds
    the balance from raw streams. Poisoning balance_gbp/total_billed_gbp must not change
    the verdict -- if it did, the control would inherit the same blindness."""
    inv = [_inv(1, "2018-08-01", -200.0), _inv(2, "2021-01-01", 100.0)]
    pay = [_pay(1, "2018-08-15", 0.0), _pay(2, "2021-01-15", 100.0)]
    honest = check_credit_balance_discharged(inv, pay, discharge_events=None)
    for i in inv:
        i["balance_gbp"] = 0.0
        i["total_billed_gbp"] = 0.0
    assert check_credit_balance_discharged(inv, pay, discharge_events=None) == honest is False


def test_failed_payments_do_not_settle_a_balance():
    inv = [_inv(1, "2018-08-01", -200.0), _inv(2, "2021-01-01", 100.0)]
    pay = [_pay(1, "2018-08-15", 0.0), _pay(2, "2021-01-15", 100.0, outcome="failed")]
    # the failed payment must not be treated as settling anything
    series = settled_balance_series(inv, pay)
    assert [d.isoformat() for d, _ in series] == ["2018-08-15"]
