"""R15 coverage for the undischarged credit-balance control.

The named defect this control exists for is REAL and is in the committed ledger: C7
invoice 841 (issued 2018-08-01) is a multi-hundred-pound catch-up credit note, and the
account's settled balance then sits at that floor for years -- with every payment
returning it to the floor rather than drawing it down. The control must FIRE on that.
The pre-existing footing control (`check_billed_clock_reconciles`) passes on the same
data, which is the blindness being closed.

NOTE ON WHAT IS ASSERTED HERE (2026-08-08): `docs/state/billing_ledger.json` is
REGENERATED by every sim run, so the credit's exact pence value moves (it was -201.96
when this was written and -202.27 one run later, which wedged the publish gate). This
test therefore asserts the SHAPE of the defect -- a material, multi-year, undischarged
CREDIT that the control fires on -- never a pinned generated figure. The control's
fires/does-not-fire proof rests on the synthetic fixtures below, which are fixed by
construction and are the real R15 evidence.
"""
from __future__ import annotations

import json
import pathlib

import pytest

from company.billing.credit_balance_control import (
    check_credit_balance_discharged,
    longest_undischarged_credit,
    settled_balance_series,
)
from company.compliance.domain_invariants import check_billed_clock_reconciles

LEDGER = pathlib.Path(__file__).resolve().parents[3] / "docs" / "state" / "billing_ledger.json"


def _c7():
    d = json.loads(LEDGER.read_text())
    return d["customers"]["C7"]


# ── the control FIRES on the real, named defect ─────────────────────────────────────
@pytest.mark.skipif(not LEDGER.is_file(), reason="billing ledger snapshot not present")
def test_fires_on_the_real_C7_undischarged_credit():
    c7 = _c7()
    worst = longest_undischarged_credit(c7["invoices"], c7["payments"])
    assert worst is not None, "control did not see the C7 credit at all"
    assert worst["days"] > 365, f"expected a multi-year hold, got {worst['days']} days"
    # A CREDIT (negative floor), and material rather than a rounding artefact. The exact
    # pence is regenerated every run -- see the module docstring; do not pin it.
    assert worst["floor_gbp"] < -50, (
        f"expected a material credit floor, got {worst['floor_gbp']}"
    )
    # and the control itself fires, with no refund recorded against the account
    assert check_credit_balance_discharged(c7["invoices"], c7["payments"],
                                           discharge_events=None) is False


@pytest.mark.skipif(not LEDGER.is_file(), reason="billing ledger snapshot not present")
def test_the_old_footing_control_passes_on_the_same_data():
    """The point of the new control: the existing one is BLIND here, because the credit
    note nets into both sides of the footing identically. This is not a criticism of
    that control -- it is why a second, lifecycle-shaped control was needed."""
    c7 = _c7()
    total_billed = round(sum(i["total_amount_gbp"] for i in c7["invoices"]), 2)
    assert check_billed_clock_reconciles(total_billed, c7["invoices"]) is True


# ── it must NOT fire on the healthy cases (or it becomes noise and gets muted) ───────
def _inv(n, d, amt):
    return {"invoice_number": n, "issue_date": d, "total_amount_gbp": amt}


def _pay(n, d, amt, outcome="success"):
    return {"invoice_number": n, "payment_date": d, "amount_gbp": amt, "outcome": outcome}


def test_silent_on_an_account_that_always_settles_to_zero():
    inv = [_inv(1, "2020-01-01", 100.0), _inv(2, "2020-02-01", 100.0)]
    pay = [_pay(1, "2020-01-15", 100.0), _pay(2, "2020-02-15", 100.0)]
    assert check_credit_balance_discharged(inv, pay, discharge_events=None) is True
    assert longest_undischarged_credit(inv, pay) is None


def test_silent_on_sub_materiality_rounding_credit():
    """C7 invoice 900 is a real -£0.22 credit note. Pennies are not a refund case."""
    inv = [_inv(1, "2020-01-01", 100.0), _inv(2, "2020-02-01", -0.22)]
    pay = [_pay(1, "2020-01-15", 100.0), _pay(2, "2024-02-15", 0.0)]
    assert check_credit_balance_discharged(inv, pay, discharge_events=None) is True


def test_silent_when_the_credit_is_offset_within_the_year():
    """Credit raised, then consumed by later bills -- the ordinary discharge path."""
    inv = [_inv(1, "2020-01-01", -50.0), _inv(2, "2020-03-01", 50.0)]
    pay = [_pay(1, "2020-01-15", 0.0), _pay(2, "2020-03-15", 0.0)]
    assert check_credit_balance_discharged(inv, pay, discharge_events=None) is True


def test_silent_when_held_long_but_a_refund_IS_recorded():
    inv = [_inv(1, "2018-08-01", -200.0), _inv(2, "2021-01-01", 100.0)]
    pay = [_pay(1, "2018-08-15", 0.0), _pay(2, "2021-01-15", 100.0)]
    assert check_credit_balance_discharged(inv, pay, discharge_events=None) is False
    assert check_credit_balance_discharged(
        inv, pay, discharge_events=[{"trigger": "customer_request"}]) is True


# ── FAIL-CLOSED: an unavailable check is a FAILED check ─────────────────────────────
@pytest.mark.parametrize("invoices,payments", [
    (None, []),
    ([], None),
    ([{"issue_date": "2020-01-01"}], []),                        # missing amount
    ([{"issue_date": "not-a-date", "total_amount_gbp": 1.0}], []),
    ([{"issue_date": "2020-01-01", "total_amount_gbp": "12.00"}], []),   # string amount
])
def test_fails_closed_on_missing_or_malformed_input(invoices, payments):
    assert check_credit_balance_discharged(invoices, payments, discharge_events=None) is False


def test_bool_is_not_accepted_as_an_amount():
    """bool is a subclass of int in Python -- a True that reached the arithmetic would
    silently count as £1. Fail closed instead."""
    inv = [{"issue_date": "2020-01-01", "total_amount_gbp": True}]
    assert settled_balance_series(inv, []) is None


# ── independence (anti-TAUTOLOGY): the control never reads the netted aggregates ─────
def test_does_not_consult_the_ledgers_own_netted_totals():
    """The blindness being fixed lives in the netted aggregates, so the control rebuilds
    the balance from raw streams. Poisoning balance_gbp/total_billed_gbp must not change
    the verdict -- if it did, the control would inherit the same blindness."""
    inv = [_inv(1, "2018-08-01", -200.0), _inv(2, "2021-01-01", 100.0)]
    pay = [_pay(1, "2018-08-15", 0.0), _pay(2, "2021-01-15", 100.0)]
    honest = check_credit_balance_discharged(inv, pay, discharge_events=None)
    for i in inv:
        i["balance_gbp"] = 0.0
        i["total_billed_gbp"] = 0.0
    assert check_credit_balance_discharged(inv, pay, discharge_events=None) == honest is False


def test_failed_payments_do_not_settle_a_balance():
    inv = [_inv(1, "2018-08-01", -200.0), _inv(2, "2021-01-01", 100.0)]
    pay = [_pay(1, "2018-08-15", 0.0), _pay(2, "2021-01-15", 100.0, outcome="failed")]
    # the failed payment must not be treated as settling anything
    series = settled_balance_series(inv, pay)
    assert [d.isoformat() for d, _ in series] == ["2018-08-15"]
