"""COUPLED-TRIAD runner for the W2_5 <-> C7 pair (life events).

This is HARNESS code. It sits OUTSIDE the epistemic wall by design and is the
ONLY layer permitted to hold the hidden SIM truth (theta) and the company's
observable-only belief (b) side by side to compute the belief-vs-truth GAP
(COUPLED_TRIAD_DESIGN.md 1.3; identical role to background/gap_metric.py). It
lives in tools/ -- NOT under company/ or saas/ -- so it is not scanned by the
epistemic verifier and may legitimately import `simulation.*`.

THE COUPLED LOOP (3 loops, COUPLED_TRIAD):

  1. SIM adds depth   -- simulation.life_events (W2_5) emits HIDDEN distress
                         events (job loss / illness / divorce / retirement /
                         new baby) that elevate a household's income_stress.
  2. COMPANY copes    -- the company NEVER sees those events. It sees only the
                         OBSERVABLE consequence: payment records generated by
                         simulation.payment_timing, an INDEPENDENT SIM model
                         that maps income_stress -> ON_TIME/LATE/DD_FAILED. The
                         company-side C7 detector (company.crm.life_event_
                         detector) infers distress from those records alone.
  3. HARNESS measures -- detection_gap(truth, flagged, harm): the harm-weighted
                         fraction of detectable distress the company MISSED,
                         normalised to the flag-nobody baseline.

R15 INDEPENDENCE. The observable channel (payment_timing) and the detector's
thresholds are set independently: payment_timing encodes the SIM's income-stress
-> payment physics; the detector encodes the supplier's own reading of "what
distress looks like", blind to those parameters. The gap is therefore a real
measurement, not a tautology. It is NOT tuned toward any target (R12/R13): the
harm weights are a principled severity ordering, frozen here.

DETERMINISM (C-S2). Every RNG is seeded from a stable hash of
(customer, year, period). No unseeded randomness. `measured_at`/`run_git_commit`
for the ledger are gathered by this harness (not by gap_metric, which never
calls a clock).
"""

from __future__ import annotations

import argparse
import hashlib
import random
import subprocess
from datetime import date, datetime, timezone

from simulation.household import make_household
from simulation.life_events import generate_life_events, household_at_date
from simulation.payment_timing import generate_payment_record

from company.crm.life_event_detector import LifeEventDetector, ObservationWindow

from background.gap_metric import detection_gap, write_gap_entry

WORLD_ATOM_ID = "W2_5_life_event_stream"
TWIN_ATOM_ID = "C7_life_event_detection"

# The distress life-event types this pair is about, with the harm weight of
# MISSING a household experiencing one. Ordering reflects income-shock severity
# (illness -> HIGH stress + medical vulnerability worst; a new baby -> MODERATE,
# lowest but still real). CURRICULUM constant (R13): a principled severity
# ordering, never fitted to move the gap.
_DISTRESS_HARM = {
    "illness": 4.0,            # -> HIGH stress + medical vulnerability
    "job_loss": 3.0,          # -> HIGH stress, income shock
    "retirement_starts": 2.0,  # -> MODERATE stress, fixed income
    "divorce": 2.0,           # -> MODERATE stress, occupancy change
    "new_baby": 1.0,          # -> MODERATE stress, new dependent
}

_RESI_HOME_TYPES = ("urban_flat", "tenement_flat", "suburban_semi", "rural_detached")
_EPCS = ("B", "C", "D", "E", "F")


def _rng(*parts) -> random.Random:
    """Deterministic RNG from a stable sha256 of the given parts (C-S2)."""
    key = ":".join(str(p) for p in parts)
    seed = int.from_bytes(hashlib.sha256(key.encode()).digest()[:8], "big")
    return random.Random(seed)


def _make_population(n: int):
    for i in range(n):
        cid = f"LEP{i:05d}"
        r = _rng("pop", cid)
        yield make_household({
            "customer_id": cid,
            "home_type": r.choice(_RESI_HOME_TYPES),
            "epc_rating": r.choice(_EPCS),
            "segment": "resi",
        })


def _monthly_payments(cid: str, year: int, period: str, income_stress):
    """12 observable monthly payment records for a period, driven by the SIM's
    income_stress -> payment model. `period` ('base'/'recent') keeps the two
    windows on independent seeds so recent noise never mirrors baseline noise."""
    r = _rng("pay", cid, year, period)
    recs = []
    for month in range(1, 13):
        due = date(year, month, 1)
        recs.append(generate_payment_record(cid, due, 95.0, income_stress, r))
    return recs


def build_scenario(n_customers: int, start_year: int, end_year: int):
    """Run the coupled loop and return (truth_set, flagged_set, harm, stats).

    Each (customer, year) is one detection instance. Truth = a distress event
    dated in that year. Observables = the customer's payment records in the
    prior year (baseline) vs that year (recent). The detector sees only the
    observables.
    """
    detector = LifeEventDetector()
    truth_set: set[str] = set()
    flagged_set: set[str] = set()
    harm: dict[str, float] = {}
    n_instances = 0
    false_positives = 0
    true_positives = 0

    for hh in _make_population(n_customers):
        cid = hh.customer_id
        events = generate_life_events(hh, start_year, end_year)

        # Index distress events by year with their harm weight.
        distress_by_year: dict[int, float] = {}
        for e in events:
            if e.event_type in _DISTRESS_HARM:
                y = int(e.event_date[:4])
                distress_by_year[y] = max(
                    distress_by_year.get(y, 0.0), _DISTRESS_HARM[e.event_type]
                )

        for year in range(start_year, end_year + 1):
            instance = f"{cid}:{year}"
            n_instances += 1

            stress_before = household_at_date(
                hh, events, f"{year - 1}-12-31"
            ).income_stress
            stress_after = household_at_date(
                hh, events, f"{year}-12-31"
            ).income_stress

            window = ObservationWindow(
                customer_id=cid,
                baseline_payments=_monthly_payments(cid, year - 1, "base", stress_before),
                recent_payments=_monthly_payments(cid, year, "recent", stress_after),
                # Consumption left unread here: detection rests purely on the
                # INDEPENDENT payment channel (cleanest R15 separation).
                baseline_consumption_kwh=None,
                recent_consumption_kwh=None,
            )
            result = detector.detect(window)

            is_truth = year in distress_by_year
            if is_truth:
                truth_set.add(instance)
                harm[instance] = distress_by_year[year]
            if result.distress_detected:
                flagged_set.add(instance)
                if is_truth:
                    true_positives += 1
                else:
                    false_positives += 1

    stats = {
        "n_customers": n_customers,
        "n_instances": n_instances,
        "n_truth": len(truth_set),
        "n_flagged": len(flagged_set),
        "true_positives": true_positives,
        "false_positives": false_positives,
        "false_positive_rate": (
            false_positives / (n_instances - len(truth_set))
            if n_instances - len(truth_set) else 0.0
        ),
    }
    return truth_set, flagged_set, harm, stats


def measure(n_customers: int = 2000, start_year: int = 2016, end_year: int = 2025):
    truth_set, flagged_set, harm, stats = build_scenario(
        n_customers, start_year, end_year
    )
    result = detection_gap(truth_set, flagged_set, harm=harm)
    # detection_gap's default note is worded for the self-rationing pair (W2_8);
    # restate it for THIS pair without touching the shared metric module.
    result.note = (
        "harm-weighted fraction of detectable life-event distress the company "
        "MISSED (W2_5 hidden events -> observable payment disruption -> C7 "
        "detection); miss-only metric, blind to false positives."
    )
    return result, stats


def _git_head() -> str | None:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], text=True
        ).strip()
    except Exception:
        return None


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--customers", type=int, default=2000)
    ap.add_argument("--start-year", type=int, default=2016)
    ap.add_argument("--end-year", type=int, default=2025)
    ap.add_argument("--write-ledger", action="store_true",
                    help="persist the measured gap into coupled_gap_ledger.json")
    args = ap.parse_args()

    result, stats = measure(args.customers, args.start_year, args.end_year)

    print(f"W2_5 <-> C7 coupled detection scenario")
    print(f"  customers   : {stats['n_customers']}")
    print(f"  instances   : {stats['n_instances']}  (customer-years)")
    print(f"  truth (distress events)  : {stats['n_truth']}")
    print(f"  flagged by detector      : {stats['n_flagged']}")
    print(f"  true positives           : {stats['true_positives']}")
    print(f"  false positives          : {stats['false_positives']}"
          f"  (fp rate {stats['false_positive_rate']:.4f})")
    print(f"  recall (caught/truth)    : "
          f"{result.components['caught']}/{result.components['truth_size']} "
          f"= {1 - result.components['miss_rate']:.4f}")
    print(f"  GAP (harm-weighted miss) : {result.gap}")
    print(f"  baseline (g0)            : {result.baseline}")

    if args.write_ledger:
        measured_at = datetime.now(timezone.utc).isoformat()
        ledger = write_gap_entry(
            WORLD_ATOM_ID, TWIN_ATOM_ID, result,
            measured_at=measured_at, run_git_commit=_git_head(),
        )
        print(f"  ledger written: {WORLD_ATOM_ID} -> gap={ledger[WORLD_ATOM_ID]['gap']}")


if __name__ == "__main__":
    main()
